// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Provisioning.proto

package signalservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProvisioningVersion int32

const (
	ProvisioningVersion_INITIAL        ProvisioningVersion = 0
	ProvisioningVersion_TABLET_SUPPORT ProvisioningVersion = 1
	ProvisioningVersion_CURRENT        ProvisioningVersion = 1
)

var ProvisioningVersion_name = map[int32]string{
	0: "INITIAL",
	1: "TABLET_SUPPORT",
	// Duplicate value: 1: "CURRENT",
}
var ProvisioningVersion_value = map[string]int32{
	"INITIAL":        0,
	"TABLET_SUPPORT": 1,
	"CURRENT":        1,
}

func (x ProvisioningVersion) Enum() *ProvisioningVersion {
	p := new(ProvisioningVersion)
	*p = x
	return p
}
func (x ProvisioningVersion) String() string {
	return proto.EnumName(ProvisioningVersion_name, int32(x))
}
func (x *ProvisioningVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProvisioningVersion_value, data, "ProvisioningVersion")
	if err != nil {
		return err
	}
	*x = ProvisioningVersion(value)
	return nil
}
func (ProvisioningVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Provisioning_6ab66841a1b13740, []int{0}
}

type ProvisionEnvelope struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionEnvelope) Reset()         { *m = ProvisionEnvelope{} }
func (m *ProvisionEnvelope) String() string { return proto.CompactTextString(m) }
func (*ProvisionEnvelope) ProtoMessage()    {}
func (*ProvisionEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_Provisioning_6ab66841a1b13740, []int{0}
}
func (m *ProvisionEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionEnvelope.Unmarshal(m, b)
}
func (m *ProvisionEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionEnvelope.Marshal(b, m, deterministic)
}
func (dst *ProvisionEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionEnvelope.Merge(dst, src)
}
func (m *ProvisionEnvelope) XXX_Size() int {
	return xxx_messageInfo_ProvisionEnvelope.Size(m)
}
func (m *ProvisionEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionEnvelope proto.InternalMessageInfo

func (m *ProvisionEnvelope) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ProvisionEnvelope) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ProvisionMessage struct {
	IdentityKeyPublic    []byte   `protobuf:"bytes,1,opt,name=identityKeyPublic" json:"identityKeyPublic,omitempty"`
	IdentityKeyPrivate   []byte   `protobuf:"bytes,2,opt,name=identityKeyPrivate" json:"identityKeyPrivate,omitempty"`
	Number               *string  `protobuf:"bytes,3,opt,name=number" json:"number,omitempty"`
	Uuid                 *string  `protobuf:"bytes,8,opt,name=uuid" json:"uuid,omitempty"`
	ProvisioningCode     *string  `protobuf:"bytes,4,opt,name=provisioningCode" json:"provisioningCode,omitempty"`
	UserAgent            *string  `protobuf:"bytes,5,opt,name=userAgent" json:"userAgent,omitempty"`
	ProfileKey           []byte   `protobuf:"bytes,6,opt,name=profileKey" json:"profileKey,omitempty"`
	ReadReceipts         *bool    `protobuf:"varint,7,opt,name=readReceipts" json:"readReceipts,omitempty"`
	ProvisioningVersion  *uint32  `protobuf:"varint,9,opt,name=provisioningVersion" json:"provisioningVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionMessage) Reset()         { *m = ProvisionMessage{} }
func (m *ProvisionMessage) String() string { return proto.CompactTextString(m) }
func (*ProvisionMessage) ProtoMessage()    {}
func (*ProvisionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_Provisioning_6ab66841a1b13740, []int{1}
}
func (m *ProvisionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionMessage.Unmarshal(m, b)
}
func (m *ProvisionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionMessage.Marshal(b, m, deterministic)
}
func (dst *ProvisionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionMessage.Merge(dst, src)
}
func (m *ProvisionMessage) XXX_Size() int {
	return xxx_messageInfo_ProvisionMessage.Size(m)
}
func (m *ProvisionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionMessage proto.InternalMessageInfo

func (m *ProvisionMessage) GetIdentityKeyPublic() []byte {
	if m != nil {
		return m.IdentityKeyPublic
	}
	return nil
}

func (m *ProvisionMessage) GetIdentityKeyPrivate() []byte {
	if m != nil {
		return m.IdentityKeyPrivate
	}
	return nil
}

func (m *ProvisionMessage) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *ProvisionMessage) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *ProvisionMessage) GetProvisioningCode() string {
	if m != nil && m.ProvisioningCode != nil {
		return *m.ProvisioningCode
	}
	return ""
}

func (m *ProvisionMessage) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

func (m *ProvisionMessage) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *ProvisionMessage) GetReadReceipts() bool {
	if m != nil && m.ReadReceipts != nil {
		return *m.ReadReceipts
	}
	return false
}

func (m *ProvisionMessage) GetProvisioningVersion() uint32 {
	if m != nil && m.ProvisioningVersion != nil {
		return *m.ProvisioningVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*ProvisionEnvelope)(nil), "signalservice.ProvisionEnvelope")
	proto.RegisterType((*ProvisionMessage)(nil), "signalservice.ProvisionMessage")
	proto.RegisterEnum("signalservice.ProvisioningVersion", ProvisioningVersion_name, ProvisioningVersion_value)
}

func init() { proto.RegisterFile("Provisioning.proto", fileDescriptor_Provisioning_6ab66841a1b13740) }

var fileDescriptor_Provisioning_6ab66841a1b13740 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x61, 0x6b, 0xdb, 0x30,
	0x10, 0x86, 0xa7, 0xac, 0x6b, 0x9b, 0x5b, 0x3b, 0xdc, 0x2b, 0x0c, 0x31, 0xc6, 0x30, 0xf9, 0x64,
	0xca, 0x30, 0xfb, 0x0b, 0x49, 0x67, 0x46, 0x68, 0xd7, 0x19, 0xcd, 0xdd, 0xd7, 0xe1, 0xc4, 0x37,
	0x57, 0xe0, 0x48, 0x42, 0x92, 0x3d, 0xfc, 0x5f, 0xf7, 0x63, 0x86, 0x45, 0x48, 0x1c, 0x92, 0x6f,
	0xa7, 0xe7, 0x3d, 0xde, 0x3b, 0x1d, 0x2f, 0x60, 0x6e, 0x75, 0x27, 0x9d, 0xd4, 0x4a, 0xaa, 0x3a,
	0x35, 0x56, 0x7b, 0x8d, 0xd7, 0x4e, 0xd6, 0xaa, 0x6c, 0x1c, 0xd9, 0x4e, 0xae, 0x69, 0x96, 0xc1,
	0xcd, 0xae, 0x29, 0x53, 0x1d, 0x35, 0xda, 0x10, 0x7e, 0x84, 0xa9, 0x69, 0x57, 0x8d, 0x5c, 0x3f,
	0x50, 0xcf, 0x59, 0xcc, 0x92, 0x2b, 0xb1, 0x07, 0x88, 0x70, 0xb6, 0xd2, 0x55, 0xcf, 0x27, 0x41,
	0x08, 0xf5, 0xec, 0xdf, 0x04, 0xa2, 0x9d, 0xcf, 0x77, 0x72, 0xae, 0xac, 0x09, 0x3f, 0xc3, 0x8d,
	0xac, 0x48, 0x79, 0xe9, 0xfb, 0x07, 0xea, 0xf3, 0x60, 0xb0, 0xb5, 0x3b, 0x16, 0x30, 0x05, 0x1c,
	0x43, 0x2b, 0xbb, 0xd2, 0xd3, 0x76, 0xc8, 0x09, 0x05, 0xdf, 0xc3, 0xb9, 0x6a, 0x37, 0x2b, 0xb2,
	0xfc, 0x75, 0xcc, 0x92, 0xa9, 0xd8, 0xbe, 0x86, 0xf5, 0xda, 0x56, 0x56, 0xfc, 0x32, 0xd0, 0x50,
	0xe3, 0x1d, 0x44, 0x66, 0x74, 0x8a, 0x7b, 0x5d, 0x11, 0x3f, 0x0b, 0xfa, 0x11, 0x1f, 0x3e, 0xdf,
	0x3a, 0xb2, 0xf3, 0x9a, 0x94, 0xe7, 0x6f, 0x42, 0xd3, 0x1e, 0xe0, 0x27, 0x00, 0x63, 0xf5, 0x1f,
	0xd9, 0xd0, 0x70, 0x9b, 0xf3, 0xb0, 0xdd, 0x88, 0xe0, 0x0c, 0xae, 0x2c, 0x95, 0x95, 0xa0, 0x35,
	0x49, 0xe3, 0x1d, 0xbf, 0x88, 0x59, 0x72, 0x29, 0x0e, 0x18, 0x7e, 0x81, 0xdb, 0xf1, 0xd4, 0x5f,
	0x64, 0x87, 0x8a, 0x4f, 0x63, 0x96, 0x5c, 0x8b, 0x53, 0xd2, 0xdd, 0x37, 0xb8, 0xcd, 0x8f, 0x31,
	0xbe, 0x85, 0x8b, 0xe5, 0xd3, 0xb2, 0x58, 0xce, 0x1f, 0xa3, 0x57, 0x88, 0xf0, 0xae, 0x98, 0x2f,
	0x1e, 0xb3, 0xe2, 0xf7, 0xcf, 0xe7, 0x3c, 0xff, 0x21, 0x8a, 0x88, 0x0d, 0x0d, 0xf7, 0xcf, 0x42,
	0x64, 0x4f, 0x45, 0xc4, 0x3e, 0x4c, 0x22, 0xb6, 0xf8, 0x0a, 0xa9, 0xb6, 0x75, 0xfa, 0xf7, 0x45,
	0x3a, 0x43, 0xd6, 0xf5, 0xce, 0xd3, 0xc6, 0xa5, 0x07, 0x91, 0x48, 0xa5, 0xf2, 0x64, 0x55, 0xd9,
	0xa4, 0xa6, 0x75, 0x2f, 0x8b, 0x83, 0x0c, 0xe5, 0x43, 0x84, 0xdc, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xdf, 0x99, 0x18, 0x14, 0x58, 0x02, 0x00, 0x00,
}
