// Code generated by protoc-gen-go.
// source: SignalService.proto
// DO NOT EDIT!

/*
Package signalservice is a generated protocol buffer package.

It is generated from these files:
	SignalService.proto
	Provisioning.proto
	WebSocketResources.proto

It has these top-level messages:
	Envelope
	Content
	CallMessage
	DataMessage
	NullMessage
	ReceiptMessage
	Verified
	SyncMessage
	AttachmentPointer
	GroupContext
	ContactDetails
	GroupDetails
	ProvisionEnvelope
	ProvisionMessage
	WebSocketRequestMessage
	WebSocketResponseMessage
	WebSocketMessage
*/
package signalservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Envelope_Type int32

const (
	Envelope_UNKNOWN       Envelope_Type = 0
	Envelope_CIPHERTEXT    Envelope_Type = 1
	Envelope_KEY_EXCHANGE  Envelope_Type = 2
	Envelope_PREKEY_BUNDLE Envelope_Type = 3
	Envelope_RECEIPT       Envelope_Type = 5
)

var Envelope_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CIPHERTEXT",
	2: "KEY_EXCHANGE",
	3: "PREKEY_BUNDLE",
	5: "RECEIPT",
}
var Envelope_Type_value = map[string]int32{
	"UNKNOWN":       0,
	"CIPHERTEXT":    1,
	"KEY_EXCHANGE":  2,
	"PREKEY_BUNDLE": 3,
	"RECEIPT":       5,
}

func (x Envelope_Type) Enum() *Envelope_Type {
	p := new(Envelope_Type)
	*p = x
	return p
}
func (x Envelope_Type) String() string {
	return proto.EnumName(Envelope_Type_name, int32(x))
}
func (x *Envelope_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Envelope_Type_value, data, "Envelope_Type")
	if err != nil {
		return err
	}
	*x = Envelope_Type(value)
	return nil
}
func (Envelope_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type DataMessage_Flags int32

const (
	DataMessage_END_SESSION             DataMessage_Flags = 1
	DataMessage_EXPIRATION_TIMER_UPDATE DataMessage_Flags = 2
	DataMessage_PROFILE_KEY_UPDATE      DataMessage_Flags = 4
)

var DataMessage_Flags_name = map[int32]string{
	1: "END_SESSION",
	2: "EXPIRATION_TIMER_UPDATE",
	4: "PROFILE_KEY_UPDATE",
}
var DataMessage_Flags_value = map[string]int32{
	"END_SESSION":             1,
	"EXPIRATION_TIMER_UPDATE": 2,
	"PROFILE_KEY_UPDATE":      4,
}

func (x DataMessage_Flags) Enum() *DataMessage_Flags {
	p := new(DataMessage_Flags)
	*p = x
	return p
}
func (x DataMessage_Flags) String() string {
	return proto.EnumName(DataMessage_Flags_name, int32(x))
}
func (x *DataMessage_Flags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataMessage_Flags_value, data, "DataMessage_Flags")
	if err != nil {
		return err
	}
	*x = DataMessage_Flags(value)
	return nil
}
func (DataMessage_Flags) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ReceiptMessage_Type int32

const (
	ReceiptMessage_DELIVERY ReceiptMessage_Type = 0
	ReceiptMessage_READ     ReceiptMessage_Type = 1
)

var ReceiptMessage_Type_name = map[int32]string{
	0: "DELIVERY",
	1: "READ",
}
var ReceiptMessage_Type_value = map[string]int32{
	"DELIVERY": 0,
	"READ":     1,
}

func (x ReceiptMessage_Type) Enum() *ReceiptMessage_Type {
	p := new(ReceiptMessage_Type)
	*p = x
	return p
}
func (x ReceiptMessage_Type) String() string {
	return proto.EnumName(ReceiptMessage_Type_name, int32(x))
}
func (x *ReceiptMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReceiptMessage_Type_value, data, "ReceiptMessage_Type")
	if err != nil {
		return err
	}
	*x = ReceiptMessage_Type(value)
	return nil
}
func (ReceiptMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type Verified_State int32

const (
	Verified_DEFAULT    Verified_State = 0
	Verified_VERIFIED   Verified_State = 1
	Verified_UNVERIFIED Verified_State = 2
)

var Verified_State_name = map[int32]string{
	0: "DEFAULT",
	1: "VERIFIED",
	2: "UNVERIFIED",
}
var Verified_State_value = map[string]int32{
	"DEFAULT":    0,
	"VERIFIED":   1,
	"UNVERIFIED": 2,
}

func (x Verified_State) Enum() *Verified_State {
	p := new(Verified_State)
	*p = x
	return p
}
func (x Verified_State) String() string {
	return proto.EnumName(Verified_State_name, int32(x))
}
func (x *Verified_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Verified_State_value, data, "Verified_State")
	if err != nil {
		return err
	}
	*x = Verified_State(value)
	return nil
}
func (Verified_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type SyncMessage_Request_Type int32

const (
	SyncMessage_Request_UNKNOWN       SyncMessage_Request_Type = 0
	SyncMessage_Request_CONTACTS      SyncMessage_Request_Type = 1
	SyncMessage_Request_GROUPS        SyncMessage_Request_Type = 2
	SyncMessage_Request_BLOCKED       SyncMessage_Request_Type = 3
	SyncMessage_Request_CONFIGURATION SyncMessage_Request_Type = 4
)

var SyncMessage_Request_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CONTACTS",
	2: "GROUPS",
	3: "BLOCKED",
	4: "CONFIGURATION",
}
var SyncMessage_Request_Type_value = map[string]int32{
	"UNKNOWN":       0,
	"CONTACTS":      1,
	"GROUPS":        2,
	"BLOCKED":       3,
	"CONFIGURATION": 4,
}

func (x SyncMessage_Request_Type) Enum() *SyncMessage_Request_Type {
	p := new(SyncMessage_Request_Type)
	*p = x
	return p
}
func (x SyncMessage_Request_Type) String() string {
	return proto.EnumName(SyncMessage_Request_Type_name, int32(x))
}
func (x *SyncMessage_Request_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncMessage_Request_Type_value, data, "SyncMessage_Request_Type")
	if err != nil {
		return err
	}
	*x = SyncMessage_Request_Type(value)
	return nil
}
func (SyncMessage_Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 4, 0}
}

type AttachmentPointer_Flags int32

const (
	AttachmentPointer_VOICE_MESSAGE AttachmentPointer_Flags = 1
)

var AttachmentPointer_Flags_name = map[int32]string{
	1: "VOICE_MESSAGE",
}
var AttachmentPointer_Flags_value = map[string]int32{
	"VOICE_MESSAGE": 1,
}

func (x AttachmentPointer_Flags) Enum() *AttachmentPointer_Flags {
	p := new(AttachmentPointer_Flags)
	*p = x
	return p
}
func (x AttachmentPointer_Flags) String() string {
	return proto.EnumName(AttachmentPointer_Flags_name, int32(x))
}
func (x *AttachmentPointer_Flags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AttachmentPointer_Flags_value, data, "AttachmentPointer_Flags")
	if err != nil {
		return err
	}
	*x = AttachmentPointer_Flags(value)
	return nil
}
func (AttachmentPointer_Flags) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type GroupContext_Type int32

const (
	GroupContext_UNKNOWN      GroupContext_Type = 0
	GroupContext_UPDATE       GroupContext_Type = 1
	GroupContext_DELIVER      GroupContext_Type = 2
	GroupContext_QUIT         GroupContext_Type = 3
	GroupContext_REQUEST_INFO GroupContext_Type = 4
)

var GroupContext_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "UPDATE",
	2: "DELIVER",
	3: "QUIT",
	4: "REQUEST_INFO",
}
var GroupContext_Type_value = map[string]int32{
	"UNKNOWN":      0,
	"UPDATE":       1,
	"DELIVER":      2,
	"QUIT":         3,
	"REQUEST_INFO": 4,
}

func (x GroupContext_Type) Enum() *GroupContext_Type {
	p := new(GroupContext_Type)
	*p = x
	return p
}
func (x GroupContext_Type) String() string {
	return proto.EnumName(GroupContext_Type_name, int32(x))
}
func (x *GroupContext_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GroupContext_Type_value, data, "GroupContext_Type")
	if err != nil {
		return err
	}
	*x = GroupContext_Type(value)
	return nil
}
func (GroupContext_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type Envelope struct {
	Type             *Envelope_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.Envelope_Type" json:"type,omitempty"`
	Source           *string        `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	SourceDevice     *uint32        `protobuf:"varint,7,opt,name=sourceDevice" json:"sourceDevice,omitempty"`
	Relay            *string        `protobuf:"bytes,3,opt,name=relay" json:"relay,omitempty"`
	Timestamp        *uint64        `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	LegacyMessage    []byte         `protobuf:"bytes,6,opt,name=legacyMessage" json:"legacyMessage,omitempty"`
	Content          []byte         `protobuf:"bytes,8,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Envelope) GetType() Envelope_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Envelope_UNKNOWN
}

func (m *Envelope) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Envelope) GetSourceDevice() uint32 {
	if m != nil && m.SourceDevice != nil {
		return *m.SourceDevice
	}
	return 0
}

func (m *Envelope) GetRelay() string {
	if m != nil && m.Relay != nil {
		return *m.Relay
	}
	return ""
}

func (m *Envelope) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Envelope) GetLegacyMessage() []byte {
	if m != nil {
		return m.LegacyMessage
	}
	return nil
}

func (m *Envelope) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Content struct {
	DataMessage      *DataMessage    `protobuf:"bytes,1,opt,name=dataMessage" json:"dataMessage,omitempty"`
	SyncMessage      *SyncMessage    `protobuf:"bytes,2,opt,name=syncMessage" json:"syncMessage,omitempty"`
	CallMessage      *CallMessage    `protobuf:"bytes,3,opt,name=callMessage" json:"callMessage,omitempty"`
	NullMessage      *NullMessage    `protobuf:"bytes,4,opt,name=nullMessage" json:"nullMessage,omitempty"`
	ReceiptMessage   *ReceiptMessage `protobuf:"bytes,5,opt,name=receiptMessage" json:"receiptMessage,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Content) GetDataMessage() *DataMessage {
	if m != nil {
		return m.DataMessage
	}
	return nil
}

func (m *Content) GetSyncMessage() *SyncMessage {
	if m != nil {
		return m.SyncMessage
	}
	return nil
}

func (m *Content) GetCallMessage() *CallMessage {
	if m != nil {
		return m.CallMessage
	}
	return nil
}

func (m *Content) GetNullMessage() *NullMessage {
	if m != nil {
		return m.NullMessage
	}
	return nil
}

func (m *Content) GetReceiptMessage() *ReceiptMessage {
	if m != nil {
		return m.ReceiptMessage
	}
	return nil
}

type CallMessage struct {
	Offer            *CallMessage_Offer       `protobuf:"bytes,1,opt,name=offer" json:"offer,omitempty"`
	Answer           *CallMessage_Answer      `protobuf:"bytes,2,opt,name=answer" json:"answer,omitempty"`
	IceUpdate        []*CallMessage_IceUpdate `protobuf:"bytes,3,rep,name=iceUpdate" json:"iceUpdate,omitempty"`
	Hangup           *CallMessage_Hangup      `protobuf:"bytes,4,opt,name=hangup" json:"hangup,omitempty"`
	Busy             *CallMessage_Busy        `protobuf:"bytes,5,opt,name=busy" json:"busy,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *CallMessage) Reset()                    { *m = CallMessage{} }
func (m *CallMessage) String() string            { return proto.CompactTextString(m) }
func (*CallMessage) ProtoMessage()               {}
func (*CallMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CallMessage) GetOffer() *CallMessage_Offer {
	if m != nil {
		return m.Offer
	}
	return nil
}

func (m *CallMessage) GetAnswer() *CallMessage_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (m *CallMessage) GetIceUpdate() []*CallMessage_IceUpdate {
	if m != nil {
		return m.IceUpdate
	}
	return nil
}

func (m *CallMessage) GetHangup() *CallMessage_Hangup {
	if m != nil {
		return m.Hangup
	}
	return nil
}

func (m *CallMessage) GetBusy() *CallMessage_Busy {
	if m != nil {
		return m.Busy
	}
	return nil
}

type CallMessage_Offer struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Offer) Reset()                    { *m = CallMessage_Offer{} }
func (m *CallMessage_Offer) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Offer) ProtoMessage()               {}
func (*CallMessage_Offer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *CallMessage_Offer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallMessage_Offer) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CallMessage_Answer struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Answer) Reset()                    { *m = CallMessage_Answer{} }
func (m *CallMessage_Answer) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Answer) ProtoMessage()               {}
func (*CallMessage_Answer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *CallMessage_Answer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallMessage_Answer) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CallMessage_IceUpdate struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SdpMid           *string `protobuf:"bytes,2,opt,name=sdpMid" json:"sdpMid,omitempty"`
	SdpMLineIndex    *uint32 `protobuf:"varint,3,opt,name=sdpMLineIndex" json:"sdpMLineIndex,omitempty"`
	Sdp              *string `protobuf:"bytes,4,opt,name=sdp" json:"sdp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_IceUpdate) Reset()                    { *m = CallMessage_IceUpdate{} }
func (m *CallMessage_IceUpdate) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_IceUpdate) ProtoMessage()               {}
func (*CallMessage_IceUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *CallMessage_IceUpdate) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallMessage_IceUpdate) GetSdpMid() string {
	if m != nil && m.SdpMid != nil {
		return *m.SdpMid
	}
	return ""
}

func (m *CallMessage_IceUpdate) GetSdpMLineIndex() uint32 {
	if m != nil && m.SdpMLineIndex != nil {
		return *m.SdpMLineIndex
	}
	return 0
}

func (m *CallMessage_IceUpdate) GetSdp() string {
	if m != nil && m.Sdp != nil {
		return *m.Sdp
	}
	return ""
}

type CallMessage_Busy struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Busy) Reset()                    { *m = CallMessage_Busy{} }
func (m *CallMessage_Busy) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Busy) ProtoMessage()               {}
func (*CallMessage_Busy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 3} }

func (m *CallMessage_Busy) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type CallMessage_Hangup struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Hangup) Reset()                    { *m = CallMessage_Hangup{} }
func (m *CallMessage_Hangup) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Hangup) ProtoMessage()               {}
func (*CallMessage_Hangup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *CallMessage_Hangup) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type DataMessage struct {
	Body             *string              `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Attachments      []*AttachmentPointer `protobuf:"bytes,2,rep,name=attachments" json:"attachments,omitempty"`
	Group            *GroupContext        `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	Flags            *uint32              `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	ExpireTimer      *uint32              `protobuf:"varint,5,opt,name=expireTimer" json:"expireTimer,omitempty"`
	ProfileKey       []byte               `protobuf:"bytes,6,opt,name=profileKey" json:"profileKey,omitempty"`
	Timestamp        *uint64              `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *DataMessage) Reset()                    { *m = DataMessage{} }
func (m *DataMessage) String() string            { return proto.CompactTextString(m) }
func (*DataMessage) ProtoMessage()               {}
func (*DataMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DataMessage) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *DataMessage) GetAttachments() []*AttachmentPointer {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *DataMessage) GetGroup() *GroupContext {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *DataMessage) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *DataMessage) GetExpireTimer() uint32 {
	if m != nil && m.ExpireTimer != nil {
		return *m.ExpireTimer
	}
	return 0
}

func (m *DataMessage) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *DataMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type NullMessage struct {
	Padding          []byte `protobuf:"bytes,1,opt,name=padding" json:"padding,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NullMessage) Reset()                    { *m = NullMessage{} }
func (m *NullMessage) String() string            { return proto.CompactTextString(m) }
func (*NullMessage) ProtoMessage()               {}
func (*NullMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NullMessage) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

type ReceiptMessage struct {
	Type             *ReceiptMessage_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.ReceiptMessage_Type" json:"type,omitempty"`
	Timestamp        []uint64             `protobuf:"varint,2,rep,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ReceiptMessage) Reset()                    { *m = ReceiptMessage{} }
func (m *ReceiptMessage) String() string            { return proto.CompactTextString(m) }
func (*ReceiptMessage) ProtoMessage()               {}
func (*ReceiptMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReceiptMessage) GetType() ReceiptMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ReceiptMessage_DELIVERY
}

func (m *ReceiptMessage) GetTimestamp() []uint64 {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Verified struct {
	Destination      *string         `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	IdentityKey      []byte          `protobuf:"bytes,2,opt,name=identityKey" json:"identityKey,omitempty"`
	State            *Verified_State `protobuf:"varint,3,opt,name=state,enum=signalservice.Verified_State" json:"state,omitempty"`
	NullMessage      []byte          `protobuf:"bytes,4,opt,name=nullMessage" json:"nullMessage,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Verified) Reset()                    { *m = Verified{} }
func (m *Verified) String() string            { return proto.CompactTextString(m) }
func (*Verified) ProtoMessage()               {}
func (*Verified) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Verified) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *Verified) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *Verified) GetState() Verified_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Verified_DEFAULT
}

func (m *Verified) GetNullMessage() []byte {
	if m != nil {
		return m.NullMessage
	}
	return nil
}

type SyncMessage struct {
	Sent             *SyncMessage_Sent          `protobuf:"bytes,1,opt,name=sent" json:"sent,omitempty"`
	Contacts         *SyncMessage_Contacts      `protobuf:"bytes,2,opt,name=contacts" json:"contacts,omitempty"`
	Groups           *SyncMessage_Groups        `protobuf:"bytes,3,opt,name=groups" json:"groups,omitempty"`
	Request          *SyncMessage_Request       `protobuf:"bytes,4,opt,name=request" json:"request,omitempty"`
	Read             []*SyncMessage_Read        `protobuf:"bytes,5,rep,name=read" json:"read,omitempty"`
	Blocked          *SyncMessage_Blocked       `protobuf:"bytes,6,opt,name=blocked" json:"blocked,omitempty"`
	Verified         *Verified                  `protobuf:"bytes,7,opt,name=verified" json:"verified,omitempty"`
	Configuration    *SyncMessage_Configuration `protobuf:"bytes,9,opt,name=configuration" json:"configuration,omitempty"`
	Padding          []byte                     `protobuf:"bytes,8,opt,name=padding" json:"padding,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *SyncMessage) Reset()                    { *m = SyncMessage{} }
func (m *SyncMessage) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()               {}
func (*SyncMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SyncMessage) GetSent() *SyncMessage_Sent {
	if m != nil {
		return m.Sent
	}
	return nil
}

func (m *SyncMessage) GetContacts() *SyncMessage_Contacts {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *SyncMessage) GetGroups() *SyncMessage_Groups {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *SyncMessage) GetRequest() *SyncMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SyncMessage) GetRead() []*SyncMessage_Read {
	if m != nil {
		return m.Read
	}
	return nil
}

func (m *SyncMessage) GetBlocked() *SyncMessage_Blocked {
	if m != nil {
		return m.Blocked
	}
	return nil
}

func (m *SyncMessage) GetVerified() *Verified {
	if m != nil {
		return m.Verified
	}
	return nil
}

func (m *SyncMessage) GetConfiguration() *SyncMessage_Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *SyncMessage) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

type SyncMessage_Sent struct {
	Destination              *string      `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	Timestamp                *uint64      `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Message                  *DataMessage `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	ExpirationStartTimestamp *uint64      `protobuf:"varint,4,opt,name=expirationStartTimestamp" json:"expirationStartTimestamp,omitempty"`
	XXX_unrecognized         []byte       `json:"-"`
}

func (m *SyncMessage_Sent) Reset()                    { *m = SyncMessage_Sent{} }
func (m *SyncMessage_Sent) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Sent) ProtoMessage()               {}
func (*SyncMessage_Sent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *SyncMessage_Sent) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *SyncMessage_Sent) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *SyncMessage_Sent) GetMessage() *DataMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SyncMessage_Sent) GetExpirationStartTimestamp() uint64 {
	if m != nil && m.ExpirationStartTimestamp != nil {
		return *m.ExpirationStartTimestamp
	}
	return 0
}

type SyncMessage_Contacts struct {
	Blob             *AttachmentPointer `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	Complete         *bool              `protobuf:"varint,2,opt,name=complete,def=0" json:"complete,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SyncMessage_Contacts) Reset()                    { *m = SyncMessage_Contacts{} }
func (m *SyncMessage_Contacts) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Contacts) ProtoMessage()               {}
func (*SyncMessage_Contacts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

const Default_SyncMessage_Contacts_Complete bool = false

func (m *SyncMessage_Contacts) GetBlob() *AttachmentPointer {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *SyncMessage_Contacts) GetComplete() bool {
	if m != nil && m.Complete != nil {
		return *m.Complete
	}
	return Default_SyncMessage_Contacts_Complete
}

type SyncMessage_Groups struct {
	Blob             *AttachmentPointer `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SyncMessage_Groups) Reset()                    { *m = SyncMessage_Groups{} }
func (m *SyncMessage_Groups) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Groups) ProtoMessage()               {}
func (*SyncMessage_Groups) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 2} }

func (m *SyncMessage_Groups) GetBlob() *AttachmentPointer {
	if m != nil {
		return m.Blob
	}
	return nil
}

type SyncMessage_Blocked struct {
	Numbers          []string `protobuf:"bytes,1,rep,name=numbers" json:"numbers,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SyncMessage_Blocked) Reset()                    { *m = SyncMessage_Blocked{} }
func (m *SyncMessage_Blocked) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Blocked) ProtoMessage()               {}
func (*SyncMessage_Blocked) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 3} }

func (m *SyncMessage_Blocked) GetNumbers() []string {
	if m != nil {
		return m.Numbers
	}
	return nil
}

type SyncMessage_Request struct {
	Type             *SyncMessage_Request_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.SyncMessage_Request_Type" json:"type,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SyncMessage_Request) Reset()                    { *m = SyncMessage_Request{} }
func (m *SyncMessage_Request) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Request) ProtoMessage()               {}
func (*SyncMessage_Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 4} }

func (m *SyncMessage_Request) GetType() SyncMessage_Request_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return SyncMessage_Request_UNKNOWN
}

type SyncMessage_Read struct {
	Sender           *string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncMessage_Read) Reset()                    { *m = SyncMessage_Read{} }
func (m *SyncMessage_Read) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Read) ProtoMessage()               {}
func (*SyncMessage_Read) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 5} }

func (m *SyncMessage_Read) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *SyncMessage_Read) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type SyncMessage_Configuration struct {
	ReadReceipts     *bool  `protobuf:"varint,1,opt,name=readReceipts" json:"readReceipts,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SyncMessage_Configuration) Reset()                    { *m = SyncMessage_Configuration{} }
func (m *SyncMessage_Configuration) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Configuration) ProtoMessage()               {}
func (*SyncMessage_Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 6} }

func (m *SyncMessage_Configuration) GetReadReceipts() bool {
	if m != nil && m.ReadReceipts != nil {
		return *m.ReadReceipts
	}
	return false
}

type AttachmentPointer struct {
	Id               *uint64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	ContentType      *string `protobuf:"bytes,2,opt,name=contentType" json:"contentType,omitempty"`
	Key              []byte  `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Size             *uint32 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Thumbnail        []byte  `protobuf:"bytes,5,opt,name=thumbnail" json:"thumbnail,omitempty"`
	Digest           []byte  `protobuf:"bytes,6,opt,name=digest" json:"digest,omitempty"`
	FileName         *string `protobuf:"bytes,7,opt,name=fileName" json:"fileName,omitempty"`
	Flags            *uint32 `protobuf:"varint,8,opt,name=flags" json:"flags,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AttachmentPointer) Reset()                    { *m = AttachmentPointer{} }
func (m *AttachmentPointer) String() string            { return proto.CompactTextString(m) }
func (*AttachmentPointer) ProtoMessage()               {}
func (*AttachmentPointer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AttachmentPointer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AttachmentPointer) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *AttachmentPointer) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AttachmentPointer) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *AttachmentPointer) GetThumbnail() []byte {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *AttachmentPointer) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *AttachmentPointer) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *AttachmentPointer) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

type GroupContext struct {
	Id               []byte             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type             *GroupContext_Type `protobuf:"varint,2,opt,name=type,enum=signalservice.GroupContext_Type" json:"type,omitempty"`
	Name             *string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Members          []string           `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	Avatar           *AttachmentPointer `protobuf:"bytes,5,opt,name=avatar" json:"avatar,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GroupContext) Reset()                    { *m = GroupContext{} }
func (m *GroupContext) String() string            { return proto.CompactTextString(m) }
func (*GroupContext) ProtoMessage()               {}
func (*GroupContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GroupContext) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GroupContext) GetType() GroupContext_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return GroupContext_UNKNOWN
}

func (m *GroupContext) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GroupContext) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GroupContext) GetAvatar() *AttachmentPointer {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type ContactDetails struct {
	Number           *string                `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Avatar           *ContactDetails_Avatar `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Color            *string                `protobuf:"bytes,4,opt,name=color" json:"color,omitempty"`
	Verified         *Verified              `protobuf:"bytes,5,opt,name=verified" json:"verified,omitempty"`
	ProfileKey       []byte                 `protobuf:"bytes,6,opt,name=profileKey" json:"profileKey,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ContactDetails) Reset()                    { *m = ContactDetails{} }
func (m *ContactDetails) String() string            { return proto.CompactTextString(m) }
func (*ContactDetails) ProtoMessage()               {}
func (*ContactDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ContactDetails) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *ContactDetails) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContactDetails) GetAvatar() *ContactDetails_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *ContactDetails) GetColor() string {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return ""
}

func (m *ContactDetails) GetVerified() *Verified {
	if m != nil {
		return m.Verified
	}
	return nil
}

func (m *ContactDetails) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

type ContactDetails_Avatar struct {
	ContentType      *string `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	Length           *uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContactDetails_Avatar) Reset()                    { *m = ContactDetails_Avatar{} }
func (m *ContactDetails_Avatar) String() string            { return proto.CompactTextString(m) }
func (*ContactDetails_Avatar) ProtoMessage()               {}
func (*ContactDetails_Avatar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

func (m *ContactDetails_Avatar) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *ContactDetails_Avatar) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type GroupDetails struct {
	Id               []byte               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string              `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Members          []string             `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	Avatar           *GroupDetails_Avatar `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Active           *bool                `protobuf:"varint,5,opt,name=active,def=1" json:"active,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GroupDetails) Reset()                    { *m = GroupDetails{} }
func (m *GroupDetails) String() string            { return proto.CompactTextString(m) }
func (*GroupDetails) ProtoMessage()               {}
func (*GroupDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

const Default_GroupDetails_Active bool = true

func (m *GroupDetails) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GroupDetails) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GroupDetails) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GroupDetails) GetAvatar() *GroupDetails_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *GroupDetails) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return Default_GroupDetails_Active
}

type GroupDetails_Avatar struct {
	ContentType      *string `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	Length           *uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupDetails_Avatar) Reset()                    { *m = GroupDetails_Avatar{} }
func (m *GroupDetails_Avatar) String() string            { return proto.CompactTextString(m) }
func (*GroupDetails_Avatar) ProtoMessage()               {}
func (*GroupDetails_Avatar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

func (m *GroupDetails_Avatar) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *GroupDetails_Avatar) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*Envelope)(nil), "signalservice.Envelope")
	proto.RegisterType((*Content)(nil), "signalservice.Content")
	proto.RegisterType((*CallMessage)(nil), "signalservice.CallMessage")
	proto.RegisterType((*CallMessage_Offer)(nil), "signalservice.CallMessage.Offer")
	proto.RegisterType((*CallMessage_Answer)(nil), "signalservice.CallMessage.Answer")
	proto.RegisterType((*CallMessage_IceUpdate)(nil), "signalservice.CallMessage.IceUpdate")
	proto.RegisterType((*CallMessage_Busy)(nil), "signalservice.CallMessage.Busy")
	proto.RegisterType((*CallMessage_Hangup)(nil), "signalservice.CallMessage.Hangup")
	proto.RegisterType((*DataMessage)(nil), "signalservice.DataMessage")
	proto.RegisterType((*NullMessage)(nil), "signalservice.NullMessage")
	proto.RegisterType((*ReceiptMessage)(nil), "signalservice.ReceiptMessage")
	proto.RegisterType((*Verified)(nil), "signalservice.Verified")
	proto.RegisterType((*SyncMessage)(nil), "signalservice.SyncMessage")
	proto.RegisterType((*SyncMessage_Sent)(nil), "signalservice.SyncMessage.Sent")
	proto.RegisterType((*SyncMessage_Contacts)(nil), "signalservice.SyncMessage.Contacts")
	proto.RegisterType((*SyncMessage_Groups)(nil), "signalservice.SyncMessage.Groups")
	proto.RegisterType((*SyncMessage_Blocked)(nil), "signalservice.SyncMessage.Blocked")
	proto.RegisterType((*SyncMessage_Request)(nil), "signalservice.SyncMessage.Request")
	proto.RegisterType((*SyncMessage_Read)(nil), "signalservice.SyncMessage.Read")
	proto.RegisterType((*SyncMessage_Configuration)(nil), "signalservice.SyncMessage.Configuration")
	proto.RegisterType((*AttachmentPointer)(nil), "signalservice.AttachmentPointer")
	proto.RegisterType((*GroupContext)(nil), "signalservice.GroupContext")
	proto.RegisterType((*ContactDetails)(nil), "signalservice.ContactDetails")
	proto.RegisterType((*ContactDetails_Avatar)(nil), "signalservice.ContactDetails.Avatar")
	proto.RegisterType((*GroupDetails)(nil), "signalservice.GroupDetails")
	proto.RegisterType((*GroupDetails_Avatar)(nil), "signalservice.GroupDetails.Avatar")
	proto.RegisterEnum("signalservice.Envelope_Type", Envelope_Type_name, Envelope_Type_value)
	proto.RegisterEnum("signalservice.DataMessage_Flags", DataMessage_Flags_name, DataMessage_Flags_value)
	proto.RegisterEnum("signalservice.ReceiptMessage_Type", ReceiptMessage_Type_name, ReceiptMessage_Type_value)
	proto.RegisterEnum("signalservice.Verified_State", Verified_State_name, Verified_State_value)
	proto.RegisterEnum("signalservice.SyncMessage_Request_Type", SyncMessage_Request_Type_name, SyncMessage_Request_Type_value)
	proto.RegisterEnum("signalservice.AttachmentPointer_Flags", AttachmentPointer_Flags_name, AttachmentPointer_Flags_value)
	proto.RegisterEnum("signalservice.GroupContext_Type", GroupContext_Type_name, GroupContext_Type_value)
}

func init() { proto.RegisterFile("SignalService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x6e, 0xdb, 0xca,
	0x15, 0x0e, 0x29, 0xea, 0xef, 0x48, 0x72, 0x99, 0x69, 0xe1, 0x08, 0x4a, 0x9a, 0x28, 0x4c, 0x80,
	0x68, 0x25, 0xb4, 0x76, 0x10, 0x34, 0xae, 0xd1, 0x42, 0x3f, 0xb4, 0x4d, 0xd8, 0x96, 0x94, 0x91,
	0xe4, 0x26, 0x2b, 0x83, 0x26, 0xc7, 0x32, 0x11, 0x8a, 0x64, 0x49, 0xca, 0x89, 0xfa, 0x00, 0x79,
	0x83, 0x6e, 0xbb, 0xef, 0x1b, 0x74, 0xdf, 0x4d, 0xd1, 0x37, 0xb8, 0x8b, 0xfb, 0x02, 0x77, 0x73,
	0x5f, 0xe1, 0x62, 0x86, 0x43, 0x89, 0xa4, 0x65, 0x25, 0x08, 0xee, 0x8e, 0x73, 0xf4, 0x7d, 0x33,
	0x3c, 0x67, 0xce, 0xf9, 0xce, 0xa1, 0xe0, 0xb7, 0x63, 0x6b, 0xe6, 0xe8, 0xf6, 0x98, 0xf8, 0xb7,
	0x96, 0x41, 0xda, 0x9e, 0xef, 0x86, 0x2e, 0xaa, 0x05, 0xcc, 0x18, 0x44, 0x46, 0xe5, 0xbf, 0x22,
	0x94, 0x54, 0xe7, 0x96, 0xd8, 0xae, 0x47, 0xd0, 0x1f, 0x40, 0x0a, 0x97, 0x1e, 0xa9, 0x0b, 0x4d,
	0xa1, 0xb5, 0xb3, 0xf7, 0xa4, 0x9d, 0x82, 0xb6, 0x63, 0x58, 0x7b, 0xb2, 0xf4, 0x08, 0x66, 0x48,
	0xb4, 0x0b, 0x85, 0xc0, 0x5d, 0xf8, 0x06, 0xa9, 0x8b, 0x4d, 0xa1, 0x55, 0xc6, 0x7c, 0x85, 0x14,
	0xa8, 0x46, 0x4f, 0x7d, 0x42, 0xb9, 0xf5, 0x62, 0x53, 0x68, 0xd5, 0x70, 0xca, 0x86, 0x7e, 0x07,
	0x79, 0x9f, 0xd8, 0xfa, 0xb2, 0x9e, 0x63, 0xd4, 0x68, 0x81, 0x9e, 0x40, 0x39, 0xb4, 0xe6, 0x24,
	0x08, 0xf5, 0xb9, 0x57, 0xcf, 0x37, 0x85, 0x96, 0x84, 0xd7, 0x06, 0xf4, 0x12, 0x6a, 0x36, 0x99,
	0xe9, 0xc6, 0xf2, 0x9c, 0x04, 0x81, 0x3e, 0x23, 0xf5, 0x42, 0x53, 0x68, 0x55, 0x71, 0xda, 0x88,
	0xea, 0x50, 0x34, 0x5c, 0x27, 0x24, 0x4e, 0x58, 0x2f, 0xb1, 0xdf, 0xe3, 0xa5, 0x32, 0x05, 0x89,
	0xbe, 0x3d, 0xaa, 0x40, 0x71, 0x3a, 0x38, 0x1d, 0x0c, 0xff, 0x36, 0x90, 0x1f, 0xa0, 0x1d, 0x80,
	0x9e, 0x36, 0x3a, 0x51, 0xf1, 0x44, 0x7d, 0x3f, 0x91, 0x05, 0x24, 0x43, 0xf5, 0x54, 0xfd, 0x70,
	0xa9, 0xbe, 0xef, 0x9d, 0x74, 0x06, 0xc7, 0xaa, 0x2c, 0xa2, 0x87, 0x50, 0x1b, 0x61, 0x95, 0x1a,
	0xbb, 0xd3, 0x41, 0xff, 0x4c, 0x95, 0x73, 0x74, 0x07, 0xac, 0xf6, 0x54, 0x6d, 0x34, 0x91, 0xf3,
	0xca, 0xff, 0x44, 0x28, 0xf6, 0xa2, 0x23, 0xd0, 0x21, 0x54, 0x4c, 0x3d, 0xd4, 0xe3, 0x17, 0xa4,
	0xb1, 0xac, 0xec, 0x35, 0x32, 0xb1, 0xec, 0xaf, 0x11, 0x38, 0x09, 0xa7, 0xec, 0x60, 0xe9, 0x18,
	0x31, 0x5b, 0xdc, 0xc8, 0x1e, 0xaf, 0x11, 0x38, 0x09, 0xa7, 0x6c, 0x43, 0xb7, 0xed, 0x98, 0x9d,
	0xdb, 0xc8, 0xee, 0xad, 0x11, 0x38, 0x09, 0xa7, 0x6c, 0x67, 0xb1, 0x66, 0x4b, 0x1b, 0xd9, 0x83,
	0x45, 0x82, 0x9d, 0x80, 0x23, 0x15, 0x76, 0x7c, 0x62, 0x10, 0xcb, 0x0b, 0xe3, 0x0d, 0xf2, 0x6c,
	0x83, 0xdf, 0x67, 0x36, 0xc0, 0x29, 0x10, 0xce, 0x90, 0x94, 0xff, 0x4b, 0x50, 0x49, 0xbc, 0x21,
	0x7a, 0x03, 0x79, 0xf7, 0xfa, 0x9a, 0xf8, 0x3c, 0x90, 0xcd, 0xfb, 0x9d, 0x69, 0x0f, 0x29, 0x0e,
	0x47, 0x70, 0xf4, 0x16, 0x0a, 0xba, 0x13, 0x7c, 0x22, 0x3e, 0x8f, 0xe1, 0xf3, 0x2d, 0xc4, 0x0e,
	0x03, 0x62, 0x4e, 0x40, 0x5d, 0x28, 0x5b, 0x06, 0x99, 0x7a, 0xa6, 0x1e, 0xd2, 0x18, 0xe6, 0x5a,
	0x95, 0xbd, 0x97, 0x5b, 0xd8, 0x5a, 0x8c, 0xc5, 0x6b, 0x1a, 0x3d, 0xfe, 0x46, 0x77, 0x66, 0x0b,
	0x8f, 0x87, 0x71, 0xdb, 0xf1, 0x27, 0x0c, 0x88, 0x39, 0x01, 0xed, 0x83, 0x74, 0xb5, 0x08, 0x96,
	0x3c, 0x7c, 0xcf, 0xb6, 0x10, 0xbb, 0x8b, 0x60, 0x89, 0x19, 0xb8, 0xf1, 0x16, 0xf2, 0xcc, 0x7d,
	0xb4, 0x03, 0xa2, 0x65, 0xb2, 0x60, 0x49, 0x58, 0xb4, 0x4c, 0xd4, 0x84, 0x8a, 0x49, 0x02, 0xc3,
	0xb7, 0xbc, 0xd0, 0x72, 0x1d, 0x5e, 0xa6, 0x49, 0x53, 0xe3, 0x00, 0x0a, 0x51, 0x00, 0xbe, 0x83,
	0xfb, 0x11, 0xca, 0x2b, 0xf7, 0xef, 0xd0, 0xa9, 0x38, 0x98, 0xde, 0xb9, 0x65, 0xae, 0xc4, 0x81,
	0xad, 0x68, 0x11, 0xd3, 0xa7, 0x33, 0xcb, 0x21, 0x9a, 0x63, 0x92, 0xcf, 0x2c, 0x4f, 0x6b, 0x38,
	0x6d, 0x44, 0x32, 0xe4, 0x02, 0x33, 0x0a, 0x5f, 0x19, 0xd3, 0xc7, 0xc6, 0x2e, 0x48, 0xd4, 0xe3,
	0xec, 0x39, 0x8d, 0x3a, 0x14, 0xa2, 0x10, 0x66, 0x7f, 0x51, 0x7e, 0x14, 0xa1, 0x92, 0x28, 0x35,
	0x84, 0x40, 0xba, 0x72, 0xcd, 0x25, 0x43, 0x94, 0x31, 0x7b, 0x46, 0x5d, 0xa8, 0xe8, 0x61, 0xa8,
	0x1b, 0x37, 0x73, 0xe2, 0x84, 0x41, 0x5d, 0x64, 0xf7, 0x9d, 0x4d, 0xb3, 0xce, 0x0a, 0x31, 0x72,
	0x2d, 0x27, 0x24, 0x3e, 0x4e, 0x92, 0xd0, 0x1f, 0x21, 0x3f, 0xf3, 0xdd, 0x85, 0xc7, 0x2b, 0xee,
	0x71, 0x86, 0x7d, 0x4c, 0x7f, 0x63, 0xfa, 0xf0, 0x39, 0xc4, 0x11, 0x92, 0xaa, 0xdf, 0xb5, 0xad,
	0xcf, 0x02, 0xe6, 0x60, 0x0d, 0x47, 0x0b, 0x1a, 0x71, 0xf2, 0xd9, 0xb3, 0x7c, 0x32, 0xb1, 0xe6,
	0xc4, 0x67, 0x29, 0x50, 0xc3, 0x49, 0x13, 0x7a, 0x0a, 0xe0, 0xf9, 0xee, 0xb5, 0x65, 0x93, 0x53,
	0xb2, 0xe4, 0xf2, 0x97, 0xb0, 0xa4, 0xf5, 0xb3, 0x98, 0xd1, 0x4f, 0xe5, 0x1c, 0xf2, 0x47, 0xec,
	0xa0, 0xdf, 0x40, 0x45, 0x1d, 0xf4, 0x2f, 0xc7, 0xea, 0x78, 0xac, 0x0d, 0x07, 0xb2, 0x80, 0x1e,
	0xc3, 0x23, 0xf5, 0xfd, 0x48, 0xc3, 0x9d, 0x89, 0x36, 0x1c, 0x5c, 0x4e, 0xb4, 0x73, 0x15, 0x5f,
	0x4e, 0x47, 0xfd, 0xce, 0x84, 0xea, 0xdf, 0x2e, 0xa0, 0x11, 0x1e, 0x1e, 0x69, 0x67, 0xea, 0x25,
	0x15, 0x41, 0x6e, 0x97, 0x94, 0x57, 0x50, 0x49, 0xe8, 0x01, 0xd5, 0x5d, 0x4f, 0x37, 0x4d, 0xcb,
	0x99, 0xb1, 0x08, 0x57, 0x71, 0xbc, 0x54, 0xbe, 0x08, 0xb0, 0x93, 0x2e, 0x7c, 0xf4, 0x26, 0xd5,
	0x6c, 0x94, 0xad, 0x2a, 0x91, 0x6c, 0x39, 0x29, 0x07, 0xe9, 0x6d, 0xa5, 0x1c, 0x7c, 0xca, 0x05,
	0xbe, 0x0a, 0xa5, 0xbe, 0x7a, 0xa6, 0x5d, 0xa8, 0xf8, 0x83, 0xfc, 0x00, 0x95, 0x40, 0xc2, 0x6a,
	0xa7, 0x2f, 0x0b, 0xca, 0x0f, 0x02, 0x94, 0x2e, 0x88, 0x6f, 0x5d, 0x5b, 0x24, 0xce, 0xef, 0xd0,
	0x72, 0x74, 0x96, 0xdf, 0xc2, 0x2a, 0xbf, 0x63, 0x13, 0x45, 0x58, 0x26, 0x71, 0x42, 0x2b, 0x5c,
	0xd2, 0x70, 0x8b, 0xcc, 0xab, 0xa4, 0x09, 0xed, 0x43, 0x3e, 0x08, 0x23, 0xa1, 0xa0, 0x7e, 0x64,
	0xd5, 0x2e, 0x3e, 0xab, 0x3d, 0xa6, 0x20, 0x1c, 0x61, 0xe9, 0xb6, 0x59, 0xa5, 0xad, 0xa6, 0xd4,
	0x54, 0xd9, 0x83, 0x3c, 0x63, 0xd0, 0x3e, 0xd3, 0x57, 0x8f, 0x3a, 0xd3, 0xb3, 0x89, 0xfc, 0x80,
	0x7a, 0x75, 0xa1, 0x62, 0xed, 0x48, 0x53, 0xfb, 0xb2, 0x40, 0xfb, 0xd6, 0x74, 0xb0, 0x5a, 0x8b,
	0xca, 0xbf, 0xca, 0x50, 0x49, 0xb4, 0x06, 0x2a, 0x24, 0x01, 0xed, 0x81, 0xc2, 0x46, 0x21, 0x49,
	0x20, 0xdb, 0x63, 0xe2, 0x84, 0x98, 0x81, 0xd1, 0x5f, 0xa1, 0x44, 0x9b, 0xa5, 0x6e, 0xb0, 0x5a,
	0xa0, 0xc4, 0x17, 0x5b, 0x88, 0x3d, 0x0e, 0xc5, 0x2b, 0x12, 0x55, 0x3e, 0x96, 0xe1, 0x01, 0x2f,
	0x86, 0xe7, 0x5b, 0xe8, 0xac, 0x30, 0x02, 0xcc, 0x09, 0xe8, 0x10, 0x8a, 0x3e, 0xf9, 0xfb, 0x82,
	0x04, 0x21, 0x57, 0x4d, 0x65, 0x0b, 0x17, 0x47, 0x48, 0x1c, 0x53, 0xa8, 0xbb, 0x3e, 0xd1, 0xcd,
	0x7a, 0x9e, 0x55, 0xf0, 0xb3, 0xad, 0x54, 0xdd, 0xc4, 0x0c, 0x4c, 0x8f, 0xbc, 0xb2, 0x5d, 0xe3,
	0x23, 0x31, 0x59, 0x2d, 0x6d, 0x3f, 0xb2, 0x1b, 0x21, 0x71, 0x4c, 0x41, 0xfb, 0x50, 0xba, 0xe5,
	0x17, 0xcc, 0x6a, 0xad, 0xb2, 0xf7, 0xe8, 0x9e, 0xfb, 0xc7, 0x2b, 0x20, 0x1a, 0x40, 0xcd, 0x70,
	0x9d, 0x6b, 0x6b, 0xb6, 0xf0, 0xa3, 0xbc, 0x2b, 0x33, 0x66, 0x6b, 0x7b, 0x98, 0xd7, 0x78, 0x9c,
	0xa6, 0x27, 0xab, 0xae, 0x94, 0xaa, 0xba, 0xc6, 0x7f, 0x04, 0x90, 0xe8, 0xd5, 0x7e, 0x43, 0xa2,
	0x67, 0xaa, 0x2a, 0x33, 0x76, 0xbd, 0x86, 0xe2, 0x7c, 0xeb, 0x4c, 0x91, 0x9c, 0x67, 0x62, 0x28,
	0x3a, 0x80, 0x3a, 0x53, 0x2e, 0x76, 0xc2, 0x38, 0xd4, 0xfd, 0x70, 0xb2, 0x3a, 0x42, 0x62, 0x47,
	0xdc, 0xfb, 0x7b, 0xc3, 0x80, 0x52, 0x9c, 0x5b, 0xe8, 0x35, 0x48, 0x57, 0xb6, 0x7b, 0x75, 0xcf,
	0x04, 0x70, 0x57, 0x9a, 0x19, 0x1a, 0x3d, 0xa7, 0x89, 0x3c, 0xf7, 0x6c, 0x12, 0x46, 0x63, 0x54,
	0xe9, 0x20, 0x7f, 0x4d, 0x59, 0x78, 0x65, 0x6e, 0xfc, 0x05, 0x0a, 0x51, 0x06, 0x7e, 0xdf, 0x11,
	0x8d, 0x17, 0x50, 0xe4, 0x29, 0x41, 0x2f, 0xc1, 0x59, 0xcc, 0xaf, 0x88, 0x1f, 0xd4, 0x85, 0x66,
	0xae, 0x55, 0xc6, 0xf1, 0xb2, 0xf1, 0x4f, 0x01, 0x8a, 0x3c, 0x57, 0xd1, 0x9f, 0x53, 0x9a, 0xf7,
	0xea, 0xeb, 0xd9, 0x9d, 0x10, 0x3e, 0xe5, 0x7c, 0xd3, 0xec, 0x5a, 0x85, 0x52, 0x6f, 0x38, 0x98,
	0x74, 0x7a, 0x93, 0xb1, 0x2c, 0x20, 0x80, 0xc2, 0x31, 0x1e, 0x4e, 0x47, 0x63, 0x59, 0xa4, 0xb0,
	0xee, 0xd9, 0xb0, 0x77, 0xaa, 0xf6, 0xe5, 0x1c, 0x1d, 0x60, 0x7b, 0xc3, 0xc1, 0x91, 0x76, 0x3c,
	0x8d, 0x04, 0x5e, 0x96, 0x1a, 0x87, 0x20, 0xd1, 0x3a, 0x60, 0x5d, 0x9a, 0x38, 0x26, 0x9f, 0xb0,
	0x68, 0x97, 0x66, 0xab, 0xed, 0x19, 0xd1, 0xd8, 0x87, 0x5a, 0x2a, 0x29, 0xe9, 0xc4, 0x4f, 0x0b,
	0x8a, 0xeb, 0x76, 0xc0, 0x36, 0x2b, 0xe1, 0x94, 0x4d, 0xf9, 0x59, 0x80, 0x87, 0x77, 0x62, 0x99,
	0x68, 0xda, 0x85, 0x78, 0xea, 0xe0, 0xe3, 0x3a, 0x75, 0x37, 0x9e, 0x3a, 0x12, 0x26, 0x3a, 0x1a,
	0x7c, 0x24, 0xd1, 0x77, 0x43, 0x15, 0xd3, 0x47, 0xda, 0xd8, 0x03, 0xeb, 0x1f, 0x84, 0x37, 0x53,
	0xf6, 0xcc, 0x1c, 0xb8, 0x59, 0xcc, 0xaf, 0x1c, 0xdd, 0xb2, 0x59, 0x27, 0xad, 0xe2, 0xb5, 0x81,
	0xba, 0x6d, 0x5a, 0x33, 0x2a, 0x35, 0x51, 0x0f, 0xe5, 0x2b, 0xd4, 0x80, 0x12, 0x6d, 0xa5, 0x03,
	0x7d, 0x1e, 0x7d, 0xb5, 0x94, 0xf1, 0x6a, 0xbd, 0xee, 0xd9, 0xa5, 0x44, 0xcf, 0x56, 0x1a, 0x71,
	0x4f, 0x7d, 0x08, 0xb5, 0x8b, 0xa1, 0xd6, 0x53, 0x2f, 0xcf, 0xd5, 0xf1, 0xb8, 0x73, 0xac, 0xca,
	0x82, 0xf2, 0x45, 0x84, 0x6a, 0xb2, 0xfb, 0x27, 0x9c, 0xad, 0x32, 0x67, 0x5f, 0xf3, 0x8c, 0x10,
	0x59, 0x46, 0x34, 0xb7, 0x0c, 0x0e, 0xc9, 0x1e, 0x88, 0x40, 0x72, 0xe8, 0x0b, 0x46, 0x5f, 0x4e,
	0xec, 0x99, 0x66, 0xe0, 0x9c, 0x44, 0x19, 0x28, 0x45, 0x19, 0xc8, 0x97, 0xe8, 0x4f, 0x50, 0xd0,
	0x6f, 0xf5, 0x50, 0xf7, 0xf9, 0x48, 0xf9, 0xf5, 0xf4, 0xe6, 0x78, 0xe5, 0x64, 0x53, 0xca, 0x01,
	0x14, 0xf8, 0x00, 0x20, 0x44, 0xdd, 0x89, 0xb5, 0x59, 0x59, 0xa4, 0x5d, 0xf6, 0xdd, 0x54, 0x9b,
	0xc8, 0x39, 0xfa, 0x05, 0x85, 0xd5, 0x77, 0x53, 0x75, 0x3c, 0xb9, 0xd4, 0x06, 0x47, 0x43, 0x59,
	0x52, 0xfe, 0x2d, 0xc2, 0x0e, 0x2f, 0xe8, 0x3e, 0x09, 0x75, 0xcb, 0x0e, 0xe8, 0x0d, 0x44, 0x35,
	0x12, 0x27, 0x5e, 0xb4, 0x5a, 0x39, 0x27, 0x26, 0x9c, 0x3b, 0x5c, 0xb9, 0x10, 0xe9, 0xcf, 0x9d,
	0x79, 0x3c, 0xb5, 0x75, 0xbb, 0xc3, 0xb0, 0xb1, 0x1b, 0xf4, 0xde, 0x0c, 0xd7, 0x76, 0x7d, 0x3e,
	0x4c, 0x46, 0x8b, 0x94, 0x78, 0xe7, 0xbf, 0x55, 0xbc, 0xbf, 0x32, 0x7e, 0x35, 0xba, 0x50, 0x88,
	0x0e, 0xcf, 0xa6, 0xb1, 0x70, 0x37, 0x8d, 0x77, 0xa1, 0x60, 0x13, 0x67, 0x16, 0xde, 0x30, 0x57,
	0x6b, 0x98, 0xaf, 0x94, 0x9f, 0x04, 0x9e, 0x34, 0x71, 0xa4, 0xb2, 0x49, 0xb3, 0x29, 0x42, 0x89,
	0xeb, 0xcf, 0xa5, 0xaf, 0xff, 0x60, 0x15, 0xbb, 0xcd, 0x4d, 0x35, 0x79, 0x54, 0x36, 0x72, 0x4f,
	0xa0, 0xa0, 0x1b, 0xa1, 0x75, 0x1b, 0x7d, 0xcc, 0x95, 0x0e, 0xa4, 0xd0, 0x5f, 0x10, 0xcc, 0x6d,
	0xbf, 0x86, 0xb3, 0x5d, 0x15, 0xda, 0xae, 0x3f, 0x6b, 0x7f, 0xba, 0xb1, 0x02, 0x8f, 0xf8, 0xc1,
	0x32, 0x08, 0xc9, 0x3c, 0xc8, 0xbc, 0x21, 0x4b, 0x4a, 0x47, 0xb7, 0xdb, 0xde, 0x22, 0xb8, 0xe9,
	0xa6, 0xff, 0xd6, 0x18, 0xf9, 0x6e, 0xe8, 0x06, 0xbf, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xdb,
	0xce, 0xca, 0xec, 0x10, 0x00, 0x00,
}
