// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SignalService.proto

package signalservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Envelope_Type int32

const (
	Envelope_UNKNOWN             Envelope_Type = 0
	Envelope_CIPHERTEXT          Envelope_Type = 1
	Envelope_KEY_EXCHANGE        Envelope_Type = 2
	Envelope_PREKEY_BUNDLE       Envelope_Type = 3
	Envelope_RECEIPT             Envelope_Type = 5
	Envelope_UNIDENTIFIED_SENDER Envelope_Type = 6
)

var Envelope_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CIPHERTEXT",
	2: "KEY_EXCHANGE",
	3: "PREKEY_BUNDLE",
	5: "RECEIPT",
	6: "UNIDENTIFIED_SENDER",
}
var Envelope_Type_value = map[string]int32{
	"UNKNOWN":             0,
	"CIPHERTEXT":          1,
	"KEY_EXCHANGE":        2,
	"PREKEY_BUNDLE":       3,
	"RECEIPT":             5,
	"UNIDENTIFIED_SENDER": 6,
}

func (x Envelope_Type) Enum() *Envelope_Type {
	p := new(Envelope_Type)
	*p = x
	return p
}
func (x Envelope_Type) String() string {
	return proto.EnumName(Envelope_Type_name, int32(x))
}
func (x *Envelope_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Envelope_Type_value, data, "Envelope_Type")
	if err != nil {
		return err
	}
	*x = Envelope_Type(value)
	return nil
}
func (Envelope_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type DataMessage_Flags int32

const (
	DataMessage_END_SESSION             DataMessage_Flags = 1
	DataMessage_EXPIRATION_TIMER_UPDATE DataMessage_Flags = 2
	DataMessage_PROFILE_KEY_UPDATE      DataMessage_Flags = 4
)

var DataMessage_Flags_name = map[int32]string{
	1: "END_SESSION",
	2: "EXPIRATION_TIMER_UPDATE",
	4: "PROFILE_KEY_UPDATE",
}
var DataMessage_Flags_value = map[string]int32{
	"END_SESSION":             1,
	"EXPIRATION_TIMER_UPDATE": 2,
	"PROFILE_KEY_UPDATE":      4,
}

func (x DataMessage_Flags) Enum() *DataMessage_Flags {
	p := new(DataMessage_Flags)
	*p = x
	return p
}
func (x DataMessage_Flags) String() string {
	return proto.EnumName(DataMessage_Flags_name, int32(x))
}
func (x *DataMessage_Flags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataMessage_Flags_value, data, "DataMessage_Flags")
	if err != nil {
		return err
	}
	*x = DataMessage_Flags(value)
	return nil
}
func (DataMessage_Flags) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

type DataMessage_ProtocolVersion int32

const (
	DataMessage_INITIAL        DataMessage_ProtocolVersion = 0
	DataMessage_MESSAGE_TIMERS DataMessage_ProtocolVersion = 1
	DataMessage_VIEW_ONCE      DataMessage_ProtocolVersion = 2
	DataMessage_CURRENT        DataMessage_ProtocolVersion = 2
)

var DataMessage_ProtocolVersion_name = map[int32]string{
	0: "INITIAL",
	1: "MESSAGE_TIMERS",
	2: "VIEW_ONCE",
	// Duplicate value: 2: "CURRENT",
}
var DataMessage_ProtocolVersion_value = map[string]int32{
	"INITIAL":        0,
	"MESSAGE_TIMERS": 1,
	"VIEW_ONCE":      2,
	"CURRENT":        2,
}

func (x DataMessage_ProtocolVersion) Enum() *DataMessage_ProtocolVersion {
	p := new(DataMessage_ProtocolVersion)
	*p = x
	return p
}
func (x DataMessage_ProtocolVersion) String() string {
	return proto.EnumName(DataMessage_ProtocolVersion_name, int32(x))
}
func (x *DataMessage_ProtocolVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataMessage_ProtocolVersion_value, data, "DataMessage_ProtocolVersion")
	if err != nil {
		return err
	}
	*x = DataMessage_ProtocolVersion(value)
	return nil
}
func (DataMessage_ProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 1}
}

type DataMessage_Contact_Phone_Type int32

const (
	DataMessage_Contact_Phone_HOME   DataMessage_Contact_Phone_Type = 1
	DataMessage_Contact_Phone_MOBILE DataMessage_Contact_Phone_Type = 2
	DataMessage_Contact_Phone_WORK   DataMessage_Contact_Phone_Type = 3
	DataMessage_Contact_Phone_CUSTOM DataMessage_Contact_Phone_Type = 4
)

var DataMessage_Contact_Phone_Type_name = map[int32]string{
	1: "HOME",
	2: "MOBILE",
	3: "WORK",
	4: "CUSTOM",
}
var DataMessage_Contact_Phone_Type_value = map[string]int32{
	"HOME":   1,
	"MOBILE": 2,
	"WORK":   3,
	"CUSTOM": 4,
}

func (x DataMessage_Contact_Phone_Type) Enum() *DataMessage_Contact_Phone_Type {
	p := new(DataMessage_Contact_Phone_Type)
	*p = x
	return p
}
func (x DataMessage_Contact_Phone_Type) String() string {
	return proto.EnumName(DataMessage_Contact_Phone_Type_name, int32(x))
}
func (x *DataMessage_Contact_Phone_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataMessage_Contact_Phone_Type_value, data, "DataMessage_Contact_Phone_Type")
	if err != nil {
		return err
	}
	*x = DataMessage_Contact_Phone_Type(value)
	return nil
}
func (DataMessage_Contact_Phone_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 1, 1, 0}
}

type DataMessage_Contact_Email_Type int32

const (
	DataMessage_Contact_Email_HOME   DataMessage_Contact_Email_Type = 1
	DataMessage_Contact_Email_MOBILE DataMessage_Contact_Email_Type = 2
	DataMessage_Contact_Email_WORK   DataMessage_Contact_Email_Type = 3
	DataMessage_Contact_Email_CUSTOM DataMessage_Contact_Email_Type = 4
)

var DataMessage_Contact_Email_Type_name = map[int32]string{
	1: "HOME",
	2: "MOBILE",
	3: "WORK",
	4: "CUSTOM",
}
var DataMessage_Contact_Email_Type_value = map[string]int32{
	"HOME":   1,
	"MOBILE": 2,
	"WORK":   3,
	"CUSTOM": 4,
}

func (x DataMessage_Contact_Email_Type) Enum() *DataMessage_Contact_Email_Type {
	p := new(DataMessage_Contact_Email_Type)
	*p = x
	return p
}
func (x DataMessage_Contact_Email_Type) String() string {
	return proto.EnumName(DataMessage_Contact_Email_Type_name, int32(x))
}
func (x *DataMessage_Contact_Email_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataMessage_Contact_Email_Type_value, data, "DataMessage_Contact_Email_Type")
	if err != nil {
		return err
	}
	*x = DataMessage_Contact_Email_Type(value)
	return nil
}
func (DataMessage_Contact_Email_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 1, 2, 0}
}

type DataMessage_Contact_PostalAddress_Type int32

const (
	DataMessage_Contact_PostalAddress_HOME   DataMessage_Contact_PostalAddress_Type = 1
	DataMessage_Contact_PostalAddress_WORK   DataMessage_Contact_PostalAddress_Type = 2
	DataMessage_Contact_PostalAddress_CUSTOM DataMessage_Contact_PostalAddress_Type = 3
)

var DataMessage_Contact_PostalAddress_Type_name = map[int32]string{
	1: "HOME",
	2: "WORK",
	3: "CUSTOM",
}
var DataMessage_Contact_PostalAddress_Type_value = map[string]int32{
	"HOME":   1,
	"WORK":   2,
	"CUSTOM": 3,
}

func (x DataMessage_Contact_PostalAddress_Type) Enum() *DataMessage_Contact_PostalAddress_Type {
	p := new(DataMessage_Contact_PostalAddress_Type)
	*p = x
	return p
}
func (x DataMessage_Contact_PostalAddress_Type) String() string {
	return proto.EnumName(DataMessage_Contact_PostalAddress_Type_name, int32(x))
}
func (x *DataMessage_Contact_PostalAddress_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataMessage_Contact_PostalAddress_Type_value, data, "DataMessage_Contact_PostalAddress_Type")
	if err != nil {
		return err
	}
	*x = DataMessage_Contact_PostalAddress_Type(value)
	return nil
}
func (DataMessage_Contact_PostalAddress_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 1, 3, 0}
}

type ReceiptMessage_Type int32

const (
	ReceiptMessage_DELIVERY ReceiptMessage_Type = 0
	ReceiptMessage_READ     ReceiptMessage_Type = 1
)

var ReceiptMessage_Type_name = map[int32]string{
	0: "DELIVERY",
	1: "READ",
}
var ReceiptMessage_Type_value = map[string]int32{
	"DELIVERY": 0,
	"READ":     1,
}

func (x ReceiptMessage_Type) Enum() *ReceiptMessage_Type {
	p := new(ReceiptMessage_Type)
	*p = x
	return p
}
func (x ReceiptMessage_Type) String() string {
	return proto.EnumName(ReceiptMessage_Type_name, int32(x))
}
func (x *ReceiptMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReceiptMessage_Type_value, data, "ReceiptMessage_Type")
	if err != nil {
		return err
	}
	*x = ReceiptMessage_Type(value)
	return nil
}
func (ReceiptMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5, 0} }

type TypingMessage_Action int32

const (
	TypingMessage_STARTED TypingMessage_Action = 0
	TypingMessage_STOPPED TypingMessage_Action = 1
)

var TypingMessage_Action_name = map[int32]string{
	0: "STARTED",
	1: "STOPPED",
}
var TypingMessage_Action_value = map[string]int32{
	"STARTED": 0,
	"STOPPED": 1,
}

func (x TypingMessage_Action) Enum() *TypingMessage_Action {
	p := new(TypingMessage_Action)
	*p = x
	return p
}
func (x TypingMessage_Action) String() string {
	return proto.EnumName(TypingMessage_Action_name, int32(x))
}
func (x *TypingMessage_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TypingMessage_Action_value, data, "TypingMessage_Action")
	if err != nil {
		return err
	}
	*x = TypingMessage_Action(value)
	return nil
}
func (TypingMessage_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{6, 0} }

type Verified_State int32

const (
	Verified_DEFAULT    Verified_State = 0
	Verified_VERIFIED   Verified_State = 1
	Verified_UNVERIFIED Verified_State = 2
)

var Verified_State_name = map[int32]string{
	0: "DEFAULT",
	1: "VERIFIED",
	2: "UNVERIFIED",
}
var Verified_State_value = map[string]int32{
	"DEFAULT":    0,
	"VERIFIED":   1,
	"UNVERIFIED": 2,
}

func (x Verified_State) Enum() *Verified_State {
	p := new(Verified_State)
	*p = x
	return p
}
func (x Verified_State) String() string {
	return proto.EnumName(Verified_State_name, int32(x))
}
func (x *Verified_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Verified_State_value, data, "Verified_State")
	if err != nil {
		return err
	}
	*x = Verified_State(value)
	return nil
}
func (Verified_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{7, 0} }

type SyncMessage_Request_Type int32

const (
	SyncMessage_Request_UNKNOWN       SyncMessage_Request_Type = 0
	SyncMessage_Request_CONTACTS      SyncMessage_Request_Type = 1
	SyncMessage_Request_GROUPS        SyncMessage_Request_Type = 2
	SyncMessage_Request_BLOCKED       SyncMessage_Request_Type = 3
	SyncMessage_Request_CONFIGURATION SyncMessage_Request_Type = 4
)

var SyncMessage_Request_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CONTACTS",
	2: "GROUPS",
	3: "BLOCKED",
	4: "CONFIGURATION",
}
var SyncMessage_Request_Type_value = map[string]int32{
	"UNKNOWN":       0,
	"CONTACTS":      1,
	"GROUPS":        2,
	"BLOCKED":       3,
	"CONFIGURATION": 4,
}

func (x SyncMessage_Request_Type) Enum() *SyncMessage_Request_Type {
	p := new(SyncMessage_Request_Type)
	*p = x
	return p
}
func (x SyncMessage_Request_Type) String() string {
	return proto.EnumName(SyncMessage_Request_Type_name, int32(x))
}
func (x *SyncMessage_Request_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncMessage_Request_Type_value, data, "SyncMessage_Request_Type")
	if err != nil {
		return err
	}
	*x = SyncMessage_Request_Type(value)
	return nil
}
func (SyncMessage_Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{8, 4, 0}
}

type SyncMessage_StickerPackOperation_Type int32

const (
	SyncMessage_StickerPackOperation_INSTALL SyncMessage_StickerPackOperation_Type = 0
	SyncMessage_StickerPackOperation_REMOVE  SyncMessage_StickerPackOperation_Type = 1
)

var SyncMessage_StickerPackOperation_Type_name = map[int32]string{
	0: "INSTALL",
	1: "REMOVE",
}
var SyncMessage_StickerPackOperation_Type_value = map[string]int32{
	"INSTALL": 0,
	"REMOVE":  1,
}

func (x SyncMessage_StickerPackOperation_Type) Enum() *SyncMessage_StickerPackOperation_Type {
	p := new(SyncMessage_StickerPackOperation_Type)
	*p = x
	return p
}
func (x SyncMessage_StickerPackOperation_Type) String() string {
	return proto.EnumName(SyncMessage_StickerPackOperation_Type_name, int32(x))
}
func (x *SyncMessage_StickerPackOperation_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncMessage_StickerPackOperation_Type_value, data, "SyncMessage_StickerPackOperation_Type")
	if err != nil {
		return err
	}
	*x = SyncMessage_StickerPackOperation_Type(value)
	return nil
}
func (SyncMessage_StickerPackOperation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{8, 7, 0}
}

type AttachmentPointer_Flags int32

const (
	AttachmentPointer_VOICE_MESSAGE AttachmentPointer_Flags = 1
)

var AttachmentPointer_Flags_name = map[int32]string{
	1: "VOICE_MESSAGE",
}
var AttachmentPointer_Flags_value = map[string]int32{
	"VOICE_MESSAGE": 1,
}

func (x AttachmentPointer_Flags) Enum() *AttachmentPointer_Flags {
	p := new(AttachmentPointer_Flags)
	*p = x
	return p
}
func (x AttachmentPointer_Flags) String() string {
	return proto.EnumName(AttachmentPointer_Flags_name, int32(x))
}
func (x *AttachmentPointer_Flags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AttachmentPointer_Flags_value, data, "AttachmentPointer_Flags")
	if err != nil {
		return err
	}
	*x = AttachmentPointer_Flags(value)
	return nil
}
func (AttachmentPointer_Flags) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

type GroupContext_Type int32

const (
	GroupContext_UNKNOWN      GroupContext_Type = 0
	GroupContext_UPDATE       GroupContext_Type = 1
	GroupContext_DELIVER      GroupContext_Type = 2
	GroupContext_QUIT         GroupContext_Type = 3
	GroupContext_REQUEST_INFO GroupContext_Type = 4
)

var GroupContext_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "UPDATE",
	2: "DELIVER",
	3: "QUIT",
	4: "REQUEST_INFO",
}
var GroupContext_Type_value = map[string]int32{
	"UNKNOWN":      0,
	"UPDATE":       1,
	"DELIVER":      2,
	"QUIT":         3,
	"REQUEST_INFO": 4,
}

func (x GroupContext_Type) Enum() *GroupContext_Type {
	p := new(GroupContext_Type)
	*p = x
	return p
}
func (x GroupContext_Type) String() string {
	return proto.EnumName(GroupContext_Type_name, int32(x))
}
func (x *GroupContext_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GroupContext_Type_value, data, "GroupContext_Type")
	if err != nil {
		return err
	}
	*x = GroupContext_Type(value)
	return nil
}
func (GroupContext_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{10, 0} }

type Envelope struct {
	Type             *Envelope_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.Envelope_Type" json:"type,omitempty"`
	Source           *string        `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	SourceDevice     *uint32        `protobuf:"varint,7,opt,name=sourceDevice" json:"sourceDevice,omitempty"`
	Relay            *string        `protobuf:"bytes,3,opt,name=relay" json:"relay,omitempty"`
	Timestamp        *uint64        `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	LegacyMessage    []byte         `protobuf:"bytes,6,opt,name=legacyMessage" json:"legacyMessage,omitempty"`
	Content          []byte         `protobuf:"bytes,8,opt,name=content" json:"content,omitempty"`
	ServerGuid       *string        `protobuf:"bytes,9,opt,name=serverGuid" json:"serverGuid,omitempty"`
	ServerTimestamp  *uint64        `protobuf:"varint,10,opt,name=serverTimestamp" json:"serverTimestamp,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Envelope) GetType() Envelope_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Envelope_UNKNOWN
}

func (m *Envelope) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Envelope) GetSourceDevice() uint32 {
	if m != nil && m.SourceDevice != nil {
		return *m.SourceDevice
	}
	return 0
}

func (m *Envelope) GetRelay() string {
	if m != nil && m.Relay != nil {
		return *m.Relay
	}
	return ""
}

func (m *Envelope) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Envelope) GetLegacyMessage() []byte {
	if m != nil {
		return m.LegacyMessage
	}
	return nil
}

func (m *Envelope) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Envelope) GetServerGuid() string {
	if m != nil && m.ServerGuid != nil {
		return *m.ServerGuid
	}
	return ""
}

func (m *Envelope) GetServerTimestamp() uint64 {
	if m != nil && m.ServerTimestamp != nil {
		return *m.ServerTimestamp
	}
	return 0
}

type Content struct {
	DataMessage      *DataMessage    `protobuf:"bytes,1,opt,name=dataMessage" json:"dataMessage,omitempty"`
	SyncMessage      *SyncMessage    `protobuf:"bytes,2,opt,name=syncMessage" json:"syncMessage,omitempty"`
	CallMessage      *CallMessage    `protobuf:"bytes,3,opt,name=callMessage" json:"callMessage,omitempty"`
	NullMessage      *NullMessage    `protobuf:"bytes,4,opt,name=nullMessage" json:"nullMessage,omitempty"`
	ReceiptMessage   *ReceiptMessage `protobuf:"bytes,5,opt,name=receiptMessage" json:"receiptMessage,omitempty"`
	TypingMessage    *TypingMessage  `protobuf:"bytes,6,opt,name=typingMessage" json:"typingMessage,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Content) GetDataMessage() *DataMessage {
	if m != nil {
		return m.DataMessage
	}
	return nil
}

func (m *Content) GetSyncMessage() *SyncMessage {
	if m != nil {
		return m.SyncMessage
	}
	return nil
}

func (m *Content) GetCallMessage() *CallMessage {
	if m != nil {
		return m.CallMessage
	}
	return nil
}

func (m *Content) GetNullMessage() *NullMessage {
	if m != nil {
		return m.NullMessage
	}
	return nil
}

func (m *Content) GetReceiptMessage() *ReceiptMessage {
	if m != nil {
		return m.ReceiptMessage
	}
	return nil
}

func (m *Content) GetTypingMessage() *TypingMessage {
	if m != nil {
		return m.TypingMessage
	}
	return nil
}

type CallMessage struct {
	Offer            *CallMessage_Offer       `protobuf:"bytes,1,opt,name=offer" json:"offer,omitempty"`
	Answer           *CallMessage_Answer      `protobuf:"bytes,2,opt,name=answer" json:"answer,omitempty"`
	IceUpdate        []*CallMessage_IceUpdate `protobuf:"bytes,3,rep,name=iceUpdate" json:"iceUpdate,omitempty"`
	Hangup           *CallMessage_Hangup      `protobuf:"bytes,4,opt,name=hangup" json:"hangup,omitempty"`
	Busy             *CallMessage_Busy        `protobuf:"bytes,5,opt,name=busy" json:"busy,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *CallMessage) Reset()                    { *m = CallMessage{} }
func (m *CallMessage) String() string            { return proto.CompactTextString(m) }
func (*CallMessage) ProtoMessage()               {}
func (*CallMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CallMessage) GetOffer() *CallMessage_Offer {
	if m != nil {
		return m.Offer
	}
	return nil
}

func (m *CallMessage) GetAnswer() *CallMessage_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (m *CallMessage) GetIceUpdate() []*CallMessage_IceUpdate {
	if m != nil {
		return m.IceUpdate
	}
	return nil
}

func (m *CallMessage) GetHangup() *CallMessage_Hangup {
	if m != nil {
		return m.Hangup
	}
	return nil
}

func (m *CallMessage) GetBusy() *CallMessage_Busy {
	if m != nil {
		return m.Busy
	}
	return nil
}

type CallMessage_Offer struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Offer) Reset()                    { *m = CallMessage_Offer{} }
func (m *CallMessage_Offer) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Offer) ProtoMessage()               {}
func (*CallMessage_Offer) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

func (m *CallMessage_Offer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallMessage_Offer) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CallMessage_Answer struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Answer) Reset()                    { *m = CallMessage_Answer{} }
func (m *CallMessage_Answer) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Answer) ProtoMessage()               {}
func (*CallMessage_Answer) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 1} }

func (m *CallMessage_Answer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallMessage_Answer) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CallMessage_IceUpdate struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SdpMid           *string `protobuf:"bytes,2,opt,name=sdpMid" json:"sdpMid,omitempty"`
	SdpMLineIndex    *uint32 `protobuf:"varint,3,opt,name=sdpMLineIndex" json:"sdpMLineIndex,omitempty"`
	Sdp              *string `protobuf:"bytes,4,opt,name=sdp" json:"sdp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_IceUpdate) Reset()                    { *m = CallMessage_IceUpdate{} }
func (m *CallMessage_IceUpdate) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_IceUpdate) ProtoMessage()               {}
func (*CallMessage_IceUpdate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 2} }

func (m *CallMessage_IceUpdate) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallMessage_IceUpdate) GetSdpMid() string {
	if m != nil && m.SdpMid != nil {
		return *m.SdpMid
	}
	return ""
}

func (m *CallMessage_IceUpdate) GetSdpMLineIndex() uint32 {
	if m != nil && m.SdpMLineIndex != nil {
		return *m.SdpMLineIndex
	}
	return 0
}

func (m *CallMessage_IceUpdate) GetSdp() string {
	if m != nil && m.Sdp != nil {
		return *m.Sdp
	}
	return ""
}

type CallMessage_Busy struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Busy) Reset()                    { *m = CallMessage_Busy{} }
func (m *CallMessage_Busy) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Busy) ProtoMessage()               {}
func (*CallMessage_Busy) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 3} }

func (m *CallMessage_Busy) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type CallMessage_Hangup struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallMessage_Hangup) Reset()                    { *m = CallMessage_Hangup{} }
func (m *CallMessage_Hangup) String() string            { return proto.CompactTextString(m) }
func (*CallMessage_Hangup) ProtoMessage()               {}
func (*CallMessage_Hangup) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 4} }

func (m *CallMessage_Hangup) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type DataMessage struct {
	Body                    *string                `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Attachments             []*AttachmentPointer   `protobuf:"bytes,2,rep,name=attachments" json:"attachments,omitempty"`
	Group                   *GroupContext          `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	Flags                   *uint32                `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	ExpireTimer             *uint32                `protobuf:"varint,5,opt,name=expireTimer" json:"expireTimer,omitempty"`
	ProfileKey              []byte                 `protobuf:"bytes,6,opt,name=profileKey" json:"profileKey,omitempty"`
	Timestamp               *uint64                `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
	Quote                   *DataMessage_Quote     `protobuf:"bytes,8,opt,name=quote" json:"quote,omitempty"`
	Contact                 []*DataMessage_Contact `protobuf:"bytes,9,rep,name=contact" json:"contact,omitempty"`
	Preview                 []*DataMessage_Preview `protobuf:"bytes,10,rep,name=preview" json:"preview,omitempty"`
	Sticker                 *DataMessage_Sticker   `protobuf:"bytes,11,opt,name=sticker" json:"sticker,omitempty"`
	RequiredProtocolVersion *uint32                `protobuf:"varint,12,opt,name=requiredProtocolVersion" json:"requiredProtocolVersion,omitempty"`
	IsViewOnce              *bool                  `protobuf:"varint,14,opt,name=isViewOnce" json:"isViewOnce,omitempty"`
	XXX_unrecognized        []byte                 `json:"-"`
}

func (m *DataMessage) Reset()                    { *m = DataMessage{} }
func (m *DataMessage) String() string            { return proto.CompactTextString(m) }
func (*DataMessage) ProtoMessage()               {}
func (*DataMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DataMessage) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *DataMessage) GetAttachments() []*AttachmentPointer {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *DataMessage) GetGroup() *GroupContext {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *DataMessage) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *DataMessage) GetExpireTimer() uint32 {
	if m != nil && m.ExpireTimer != nil {
		return *m.ExpireTimer
	}
	return 0
}

func (m *DataMessage) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *DataMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *DataMessage) GetQuote() *DataMessage_Quote {
	if m != nil {
		return m.Quote
	}
	return nil
}

func (m *DataMessage) GetContact() []*DataMessage_Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *DataMessage) GetPreview() []*DataMessage_Preview {
	if m != nil {
		return m.Preview
	}
	return nil
}

func (m *DataMessage) GetSticker() *DataMessage_Sticker {
	if m != nil {
		return m.Sticker
	}
	return nil
}

func (m *DataMessage) GetRequiredProtocolVersion() uint32 {
	if m != nil && m.RequiredProtocolVersion != nil {
		return *m.RequiredProtocolVersion
	}
	return 0
}

func (m *DataMessage) GetIsViewOnce() bool {
	if m != nil && m.IsViewOnce != nil {
		return *m.IsViewOnce
	}
	return false
}

type DataMessage_Quote struct {
	Id               *uint64                               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Author           *string                               `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Text             *string                               `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Attachments      []*DataMessage_Quote_QuotedAttachment `protobuf:"bytes,4,rep,name=attachments" json:"attachments,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *DataMessage_Quote) Reset()                    { *m = DataMessage_Quote{} }
func (m *DataMessage_Quote) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Quote) ProtoMessage()               {}
func (*DataMessage_Quote) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

func (m *DataMessage_Quote) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DataMessage_Quote) GetAuthor() string {
	if m != nil && m.Author != nil {
		return *m.Author
	}
	return ""
}

func (m *DataMessage_Quote) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *DataMessage_Quote) GetAttachments() []*DataMessage_Quote_QuotedAttachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

type DataMessage_Quote_QuotedAttachment struct {
	ContentType      *string            `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	FileName         *string            `protobuf:"bytes,2,opt,name=fileName" json:"fileName,omitempty"`
	Thumbnail        *AttachmentPointer `protobuf:"bytes,3,opt,name=thumbnail" json:"thumbnail,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DataMessage_Quote_QuotedAttachment) Reset()         { *m = DataMessage_Quote_QuotedAttachment{} }
func (m *DataMessage_Quote_QuotedAttachment) String() string { return proto.CompactTextString(m) }
func (*DataMessage_Quote_QuotedAttachment) ProtoMessage()    {}
func (*DataMessage_Quote_QuotedAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0, 0}
}

func (m *DataMessage_Quote_QuotedAttachment) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *DataMessage_Quote_QuotedAttachment) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *DataMessage_Quote_QuotedAttachment) GetThumbnail() *AttachmentPointer {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

type DataMessage_Contact struct {
	Name             *DataMessage_Contact_Name            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Number           []*DataMessage_Contact_Phone         `protobuf:"bytes,3,rep,name=number" json:"number,omitempty"`
	Email            []*DataMessage_Contact_Email         `protobuf:"bytes,4,rep,name=email" json:"email,omitempty"`
	Address          []*DataMessage_Contact_PostalAddress `protobuf:"bytes,5,rep,name=address" json:"address,omitempty"`
	Avatar           *DataMessage_Contact_Avatar          `protobuf:"bytes,6,opt,name=avatar" json:"avatar,omitempty"`
	Organization     *string                              `protobuf:"bytes,7,opt,name=organization" json:"organization,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *DataMessage_Contact) Reset()                    { *m = DataMessage_Contact{} }
func (m *DataMessage_Contact) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Contact) ProtoMessage()               {}
func (*DataMessage_Contact) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 1} }

func (m *DataMessage_Contact) GetName() *DataMessage_Contact_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *DataMessage_Contact) GetNumber() []*DataMessage_Contact_Phone {
	if m != nil {
		return m.Number
	}
	return nil
}

func (m *DataMessage_Contact) GetEmail() []*DataMessage_Contact_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *DataMessage_Contact) GetAddress() []*DataMessage_Contact_PostalAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DataMessage_Contact) GetAvatar() *DataMessage_Contact_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *DataMessage_Contact) GetOrganization() string {
	if m != nil && m.Organization != nil {
		return *m.Organization
	}
	return ""
}

type DataMessage_Contact_Name struct {
	GivenName        *string `protobuf:"bytes,1,opt,name=givenName" json:"givenName,omitempty"`
	FamilyName       *string `protobuf:"bytes,2,opt,name=familyName" json:"familyName,omitempty"`
	Prefix           *string `protobuf:"bytes,3,opt,name=prefix" json:"prefix,omitempty"`
	Suffix           *string `protobuf:"bytes,4,opt,name=suffix" json:"suffix,omitempty"`
	MiddleName       *string `protobuf:"bytes,5,opt,name=middleName" json:"middleName,omitempty"`
	DisplayName      *string `protobuf:"bytes,6,opt,name=displayName" json:"displayName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DataMessage_Contact_Name) Reset()                    { *m = DataMessage_Contact_Name{} }
func (m *DataMessage_Contact_Name) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Contact_Name) ProtoMessage()               {}
func (*DataMessage_Contact_Name) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 1, 0} }

func (m *DataMessage_Contact_Name) GetGivenName() string {
	if m != nil && m.GivenName != nil {
		return *m.GivenName
	}
	return ""
}

func (m *DataMessage_Contact_Name) GetFamilyName() string {
	if m != nil && m.FamilyName != nil {
		return *m.FamilyName
	}
	return ""
}

func (m *DataMessage_Contact_Name) GetPrefix() string {
	if m != nil && m.Prefix != nil {
		return *m.Prefix
	}
	return ""
}

func (m *DataMessage_Contact_Name) GetSuffix() string {
	if m != nil && m.Suffix != nil {
		return *m.Suffix
	}
	return ""
}

func (m *DataMessage_Contact_Name) GetMiddleName() string {
	if m != nil && m.MiddleName != nil {
		return *m.MiddleName
	}
	return ""
}

func (m *DataMessage_Contact_Name) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

type DataMessage_Contact_Phone struct {
	Value            *string                         `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Type             *DataMessage_Contact_Phone_Type `protobuf:"varint,2,opt,name=type,enum=signalservice.DataMessage_Contact_Phone_Type" json:"type,omitempty"`
	Label            *string                         `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *DataMessage_Contact_Phone) Reset()                    { *m = DataMessage_Contact_Phone{} }
func (m *DataMessage_Contact_Phone) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Contact_Phone) ProtoMessage()               {}
func (*DataMessage_Contact_Phone) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 1, 1} }

func (m *DataMessage_Contact_Phone) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *DataMessage_Contact_Phone) GetType() DataMessage_Contact_Phone_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return DataMessage_Contact_Phone_HOME
}

func (m *DataMessage_Contact_Phone) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

type DataMessage_Contact_Email struct {
	Value            *string                         `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Type             *DataMessage_Contact_Email_Type `protobuf:"varint,2,opt,name=type,enum=signalservice.DataMessage_Contact_Email_Type" json:"type,omitempty"`
	Label            *string                         `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *DataMessage_Contact_Email) Reset()                    { *m = DataMessage_Contact_Email{} }
func (m *DataMessage_Contact_Email) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Contact_Email) ProtoMessage()               {}
func (*DataMessage_Contact_Email) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 1, 2} }

func (m *DataMessage_Contact_Email) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *DataMessage_Contact_Email) GetType() DataMessage_Contact_Email_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return DataMessage_Contact_Email_HOME
}

func (m *DataMessage_Contact_Email) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

type DataMessage_Contact_PostalAddress struct {
	Type             *DataMessage_Contact_PostalAddress_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.DataMessage_Contact_PostalAddress_Type" json:"type,omitempty"`
	Label            *string                                 `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Street           *string                                 `protobuf:"bytes,3,opt,name=street" json:"street,omitempty"`
	Pobox            *string                                 `protobuf:"bytes,4,opt,name=pobox" json:"pobox,omitempty"`
	Neighborhood     *string                                 `protobuf:"bytes,5,opt,name=neighborhood" json:"neighborhood,omitempty"`
	City             *string                                 `protobuf:"bytes,6,opt,name=city" json:"city,omitempty"`
	Region           *string                                 `protobuf:"bytes,7,opt,name=region" json:"region,omitempty"`
	Postcode         *string                                 `protobuf:"bytes,8,opt,name=postcode" json:"postcode,omitempty"`
	Country          *string                                 `protobuf:"bytes,9,opt,name=country" json:"country,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *DataMessage_Contact_PostalAddress) Reset()         { *m = DataMessage_Contact_PostalAddress{} }
func (m *DataMessage_Contact_PostalAddress) String() string { return proto.CompactTextString(m) }
func (*DataMessage_Contact_PostalAddress) ProtoMessage()    {}
func (*DataMessage_Contact_PostalAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 1, 3}
}

func (m *DataMessage_Contact_PostalAddress) GetType() DataMessage_Contact_PostalAddress_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return DataMessage_Contact_PostalAddress_HOME
}

func (m *DataMessage_Contact_PostalAddress) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetStreet() string {
	if m != nil && m.Street != nil {
		return *m.Street
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetPobox() string {
	if m != nil && m.Pobox != nil {
		return *m.Pobox
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetNeighborhood() string {
	if m != nil && m.Neighborhood != nil {
		return *m.Neighborhood
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetRegion() string {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetPostcode() string {
	if m != nil && m.Postcode != nil {
		return *m.Postcode
	}
	return ""
}

func (m *DataMessage_Contact_PostalAddress) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

type DataMessage_Contact_Avatar struct {
	Avatar           *AttachmentPointer `protobuf:"bytes,1,opt,name=avatar" json:"avatar,omitempty"`
	IsProfile        *bool              `protobuf:"varint,2,opt,name=isProfile" json:"isProfile,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DataMessage_Contact_Avatar) Reset()         { *m = DataMessage_Contact_Avatar{} }
func (m *DataMessage_Contact_Avatar) String() string { return proto.CompactTextString(m) }
func (*DataMessage_Contact_Avatar) ProtoMessage()    {}
func (*DataMessage_Contact_Avatar) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 1, 4}
}

func (m *DataMessage_Contact_Avatar) GetAvatar() *AttachmentPointer {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *DataMessage_Contact_Avatar) GetIsProfile() bool {
	if m != nil && m.IsProfile != nil {
		return *m.IsProfile
	}
	return false
}

type DataMessage_Preview struct {
	Url              *string            `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Title            *string            `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Image            *AttachmentPointer `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DataMessage_Preview) Reset()                    { *m = DataMessage_Preview{} }
func (m *DataMessage_Preview) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Preview) ProtoMessage()               {}
func (*DataMessage_Preview) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 2} }

func (m *DataMessage_Preview) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *DataMessage_Preview) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *DataMessage_Preview) GetImage() *AttachmentPointer {
	if m != nil {
		return m.Image
	}
	return nil
}

type DataMessage_Sticker struct {
	PackId           []byte             `protobuf:"bytes,1,opt,name=packId" json:"packId,omitempty"`
	PackKey          []byte             `protobuf:"bytes,2,opt,name=packKey" json:"packKey,omitempty"`
	StickerId        *uint32            `protobuf:"varint,3,opt,name=stickerId" json:"stickerId,omitempty"`
	Data             *AttachmentPointer `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DataMessage_Sticker) Reset()                    { *m = DataMessage_Sticker{} }
func (m *DataMessage_Sticker) String() string            { return proto.CompactTextString(m) }
func (*DataMessage_Sticker) ProtoMessage()               {}
func (*DataMessage_Sticker) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 3} }

func (m *DataMessage_Sticker) GetPackId() []byte {
	if m != nil {
		return m.PackId
	}
	return nil
}

func (m *DataMessage_Sticker) GetPackKey() []byte {
	if m != nil {
		return m.PackKey
	}
	return nil
}

func (m *DataMessage_Sticker) GetStickerId() uint32 {
	if m != nil && m.StickerId != nil {
		return *m.StickerId
	}
	return 0
}

func (m *DataMessage_Sticker) GetData() *AttachmentPointer {
	if m != nil {
		return m.Data
	}
	return nil
}

type NullMessage struct {
	Padding          []byte `protobuf:"bytes,1,opt,name=padding" json:"padding,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NullMessage) Reset()                    { *m = NullMessage{} }
func (m *NullMessage) String() string            { return proto.CompactTextString(m) }
func (*NullMessage) ProtoMessage()               {}
func (*NullMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *NullMessage) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

type ReceiptMessage struct {
	Type             *ReceiptMessage_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.ReceiptMessage_Type" json:"type,omitempty"`
	Timestamp        []uint64             `protobuf:"varint,2,rep,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ReceiptMessage) Reset()                    { *m = ReceiptMessage{} }
func (m *ReceiptMessage) String() string            { return proto.CompactTextString(m) }
func (*ReceiptMessage) ProtoMessage()               {}
func (*ReceiptMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ReceiptMessage) GetType() ReceiptMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ReceiptMessage_DELIVERY
}

func (m *ReceiptMessage) GetTimestamp() []uint64 {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type TypingMessage struct {
	Timestamp        *uint64               `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Action           *TypingMessage_Action `protobuf:"varint,2,opt,name=action,enum=signalservice.TypingMessage_Action" json:"action,omitempty"`
	GroupId          []byte                `protobuf:"bytes,3,opt,name=groupId" json:"groupId,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *TypingMessage) Reset()                    { *m = TypingMessage{} }
func (m *TypingMessage) String() string            { return proto.CompactTextString(m) }
func (*TypingMessage) ProtoMessage()               {}
func (*TypingMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *TypingMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *TypingMessage) GetAction() TypingMessage_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return TypingMessage_STARTED
}

func (m *TypingMessage) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

type Verified struct {
	Destination      *string         `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	IdentityKey      []byte          `protobuf:"bytes,2,opt,name=identityKey" json:"identityKey,omitempty"`
	State            *Verified_State `protobuf:"varint,3,opt,name=state,enum=signalservice.Verified_State" json:"state,omitempty"`
	NullMessage      []byte          `protobuf:"bytes,4,opt,name=nullMessage" json:"nullMessage,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Verified) Reset()                    { *m = Verified{} }
func (m *Verified) String() string            { return proto.CompactTextString(m) }
func (*Verified) ProtoMessage()               {}
func (*Verified) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Verified) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *Verified) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *Verified) GetState() Verified_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Verified_DEFAULT
}

func (m *Verified) GetNullMessage() []byte {
	if m != nil {
		return m.NullMessage
	}
	return nil
}

type SyncMessage struct {
	Sent                 *SyncMessage_Sent                   `protobuf:"bytes,1,opt,name=sent" json:"sent,omitempty"`
	Contacts             *SyncMessage_Contacts               `protobuf:"bytes,2,opt,name=contacts" json:"contacts,omitempty"`
	Groups               *SyncMessage_Groups                 `protobuf:"bytes,3,opt,name=groups" json:"groups,omitempty"`
	Request              *SyncMessage_Request                `protobuf:"bytes,4,opt,name=request" json:"request,omitempty"`
	Read                 []*SyncMessage_Read                 `protobuf:"bytes,5,rep,name=read" json:"read,omitempty"`
	Blocked              *SyncMessage_Blocked                `protobuf:"bytes,6,opt,name=blocked" json:"blocked,omitempty"`
	Verified             *Verified                           `protobuf:"bytes,7,opt,name=verified" json:"verified,omitempty"`
	Configuration        *SyncMessage_Configuration          `protobuf:"bytes,9,opt,name=configuration" json:"configuration,omitempty"`
	Padding              []byte                              `protobuf:"bytes,8,opt,name=padding" json:"padding,omitempty"`
	StickerPackOperation []*SyncMessage_StickerPackOperation `protobuf:"bytes,10,rep,name=stickerPackOperation" json:"stickerPackOperation,omitempty"`
	ViewOnceOpen         *SyncMessage_ViewOnceOpen           `protobuf:"bytes,11,opt,name=viewOnceOpen" json:"viewOnceOpen,omitempty"`
	XXX_unrecognized     []byte                              `json:"-"`
}

func (m *SyncMessage) Reset()                    { *m = SyncMessage{} }
func (m *SyncMessage) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()               {}
func (*SyncMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *SyncMessage) GetSent() *SyncMessage_Sent {
	if m != nil {
		return m.Sent
	}
	return nil
}

func (m *SyncMessage) GetContacts() *SyncMessage_Contacts {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *SyncMessage) GetGroups() *SyncMessage_Groups {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *SyncMessage) GetRequest() *SyncMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SyncMessage) GetRead() []*SyncMessage_Read {
	if m != nil {
		return m.Read
	}
	return nil
}

func (m *SyncMessage) GetBlocked() *SyncMessage_Blocked {
	if m != nil {
		return m.Blocked
	}
	return nil
}

func (m *SyncMessage) GetVerified() *Verified {
	if m != nil {
		return m.Verified
	}
	return nil
}

func (m *SyncMessage) GetConfiguration() *SyncMessage_Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *SyncMessage) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

func (m *SyncMessage) GetStickerPackOperation() []*SyncMessage_StickerPackOperation {
	if m != nil {
		return m.StickerPackOperation
	}
	return nil
}

func (m *SyncMessage) GetViewOnceOpen() *SyncMessage_ViewOnceOpen {
	if m != nil {
		return m.ViewOnceOpen
	}
	return nil
}

type SyncMessage_Sent struct {
	Destination              *string                                        `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	Timestamp                *uint64                                        `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Message                  *DataMessage                                   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	ExpirationStartTimestamp *uint64                                        `protobuf:"varint,4,opt,name=expirationStartTimestamp" json:"expirationStartTimestamp,omitempty"`
	UnidentifiedStatus       []*SyncMessage_Sent_UnidentifiedDeliveryStatus `protobuf:"bytes,5,rep,name=unidentifiedStatus" json:"unidentifiedStatus,omitempty"`
	IsRecipientUpdate        *bool                                          `protobuf:"varint,6,opt,name=isRecipientUpdate,def=0" json:"isRecipientUpdate,omitempty"`
	XXX_unrecognized         []byte                                         `json:"-"`
}

func (m *SyncMessage_Sent) Reset()                    { *m = SyncMessage_Sent{} }
func (m *SyncMessage_Sent) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Sent) ProtoMessage()               {}
func (*SyncMessage_Sent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 0} }

const Default_SyncMessage_Sent_IsRecipientUpdate bool = false

func (m *SyncMessage_Sent) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *SyncMessage_Sent) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *SyncMessage_Sent) GetMessage() *DataMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SyncMessage_Sent) GetExpirationStartTimestamp() uint64 {
	if m != nil && m.ExpirationStartTimestamp != nil {
		return *m.ExpirationStartTimestamp
	}
	return 0
}

func (m *SyncMessage_Sent) GetUnidentifiedStatus() []*SyncMessage_Sent_UnidentifiedDeliveryStatus {
	if m != nil {
		return m.UnidentifiedStatus
	}
	return nil
}

func (m *SyncMessage_Sent) GetIsRecipientUpdate() bool {
	if m != nil && m.IsRecipientUpdate != nil {
		return *m.IsRecipientUpdate
	}
	return Default_SyncMessage_Sent_IsRecipientUpdate
}

type SyncMessage_Sent_UnidentifiedDeliveryStatus struct {
	Destination      *string `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	Unidentified     *bool   `protobuf:"varint,2,opt,name=unidentified" json:"unidentified,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncMessage_Sent_UnidentifiedDeliveryStatus) Reset() {
	*m = SyncMessage_Sent_UnidentifiedDeliveryStatus{}
}
func (m *SyncMessage_Sent_UnidentifiedDeliveryStatus) String() string {
	return proto.CompactTextString(m)
}
func (*SyncMessage_Sent_UnidentifiedDeliveryStatus) ProtoMessage() {}
func (*SyncMessage_Sent_UnidentifiedDeliveryStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{8, 0, 0}
}

func (m *SyncMessage_Sent_UnidentifiedDeliveryStatus) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *SyncMessage_Sent_UnidentifiedDeliveryStatus) GetUnidentified() bool {
	if m != nil && m.Unidentified != nil {
		return *m.Unidentified
	}
	return false
}

type SyncMessage_Contacts struct {
	Blob             *AttachmentPointer `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	Complete         *bool              `protobuf:"varint,2,opt,name=complete,def=0" json:"complete,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SyncMessage_Contacts) Reset()                    { *m = SyncMessage_Contacts{} }
func (m *SyncMessage_Contacts) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Contacts) ProtoMessage()               {}
func (*SyncMessage_Contacts) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 1} }

const Default_SyncMessage_Contacts_Complete bool = false

func (m *SyncMessage_Contacts) GetBlob() *AttachmentPointer {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *SyncMessage_Contacts) GetComplete() bool {
	if m != nil && m.Complete != nil {
		return *m.Complete
	}
	return Default_SyncMessage_Contacts_Complete
}

type SyncMessage_Groups struct {
	Blob             *AttachmentPointer `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SyncMessage_Groups) Reset()                    { *m = SyncMessage_Groups{} }
func (m *SyncMessage_Groups) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Groups) ProtoMessage()               {}
func (*SyncMessage_Groups) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 2} }

func (m *SyncMessage_Groups) GetBlob() *AttachmentPointer {
	if m != nil {
		return m.Blob
	}
	return nil
}

type SyncMessage_Blocked struct {
	Numbers          []string `protobuf:"bytes,1,rep,name=numbers" json:"numbers,omitempty"`
	GroupIds         [][]byte `protobuf:"bytes,2,rep,name=groupIds" json:"groupIds,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SyncMessage_Blocked) Reset()                    { *m = SyncMessage_Blocked{} }
func (m *SyncMessage_Blocked) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Blocked) ProtoMessage()               {}
func (*SyncMessage_Blocked) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 3} }

func (m *SyncMessage_Blocked) GetNumbers() []string {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *SyncMessage_Blocked) GetGroupIds() [][]byte {
	if m != nil {
		return m.GroupIds
	}
	return nil
}

type SyncMessage_Request struct {
	Type             *SyncMessage_Request_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.SyncMessage_Request_Type" json:"type,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SyncMessage_Request) Reset()                    { *m = SyncMessage_Request{} }
func (m *SyncMessage_Request) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Request) ProtoMessage()               {}
func (*SyncMessage_Request) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 4} }

func (m *SyncMessage_Request) GetType() SyncMessage_Request_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return SyncMessage_Request_UNKNOWN
}

type SyncMessage_Read struct {
	Sender           *string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncMessage_Read) Reset()                    { *m = SyncMessage_Read{} }
func (m *SyncMessage_Read) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Read) ProtoMessage()               {}
func (*SyncMessage_Read) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 5} }

func (m *SyncMessage_Read) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *SyncMessage_Read) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type SyncMessage_Configuration struct {
	ReadReceipts                   *bool  `protobuf:"varint,1,opt,name=readReceipts" json:"readReceipts,omitempty"`
	UnidentifiedDeliveryIndicators *bool  `protobuf:"varint,2,opt,name=unidentifiedDeliveryIndicators" json:"unidentifiedDeliveryIndicators,omitempty"`
	TypingIndicators               *bool  `protobuf:"varint,3,opt,name=typingIndicators" json:"typingIndicators,omitempty"`
	LinkPreviews                   *bool  `protobuf:"varint,4,opt,name=linkPreviews" json:"linkPreviews,omitempty"`
	XXX_unrecognized               []byte `json:"-"`
}

func (m *SyncMessage_Configuration) Reset()                    { *m = SyncMessage_Configuration{} }
func (m *SyncMessage_Configuration) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_Configuration) ProtoMessage()               {}
func (*SyncMessage_Configuration) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 6} }

func (m *SyncMessage_Configuration) GetReadReceipts() bool {
	if m != nil && m.ReadReceipts != nil {
		return *m.ReadReceipts
	}
	return false
}

func (m *SyncMessage_Configuration) GetUnidentifiedDeliveryIndicators() bool {
	if m != nil && m.UnidentifiedDeliveryIndicators != nil {
		return *m.UnidentifiedDeliveryIndicators
	}
	return false
}

func (m *SyncMessage_Configuration) GetTypingIndicators() bool {
	if m != nil && m.TypingIndicators != nil {
		return *m.TypingIndicators
	}
	return false
}

func (m *SyncMessage_Configuration) GetLinkPreviews() bool {
	if m != nil && m.LinkPreviews != nil {
		return *m.LinkPreviews
	}
	return false
}

type SyncMessage_StickerPackOperation struct {
	PackId           []byte                                 `protobuf:"bytes,1,opt,name=packId" json:"packId,omitempty"`
	PackKey          []byte                                 `protobuf:"bytes,2,opt,name=packKey" json:"packKey,omitempty"`
	Type             *SyncMessage_StickerPackOperation_Type `protobuf:"varint,3,opt,name=type,enum=signalservice.SyncMessage_StickerPackOperation_Type" json:"type,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *SyncMessage_StickerPackOperation) Reset()         { *m = SyncMessage_StickerPackOperation{} }
func (m *SyncMessage_StickerPackOperation) String() string { return proto.CompactTextString(m) }
func (*SyncMessage_StickerPackOperation) ProtoMessage()    {}
func (*SyncMessage_StickerPackOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{8, 7}
}

func (m *SyncMessage_StickerPackOperation) GetPackId() []byte {
	if m != nil {
		return m.PackId
	}
	return nil
}

func (m *SyncMessage_StickerPackOperation) GetPackKey() []byte {
	if m != nil {
		return m.PackKey
	}
	return nil
}

func (m *SyncMessage_StickerPackOperation) GetType() SyncMessage_StickerPackOperation_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return SyncMessage_StickerPackOperation_INSTALL
}

type SyncMessage_ViewOnceOpen struct {
	Sender           *string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncMessage_ViewOnceOpen) Reset()                    { *m = SyncMessage_ViewOnceOpen{} }
func (m *SyncMessage_ViewOnceOpen) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage_ViewOnceOpen) ProtoMessage()               {}
func (*SyncMessage_ViewOnceOpen) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 8} }

func (m *SyncMessage_ViewOnceOpen) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *SyncMessage_ViewOnceOpen) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type AttachmentPointer struct {
	Id               *uint64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	ContentType      *string `protobuf:"bytes,2,opt,name=contentType" json:"contentType,omitempty"`
	Key              []byte  `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Size             *uint32 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Thumbnail        []byte  `protobuf:"bytes,5,opt,name=thumbnail" json:"thumbnail,omitempty"`
	Digest           []byte  `protobuf:"bytes,6,opt,name=digest" json:"digest,omitempty"`
	FileName         *string `protobuf:"bytes,7,opt,name=fileName" json:"fileName,omitempty"`
	Flags            *uint32 `protobuf:"varint,8,opt,name=flags" json:"flags,omitempty"`
	Width            *uint32 `protobuf:"varint,9,opt,name=width" json:"width,omitempty"`
	Height           *uint32 `protobuf:"varint,10,opt,name=height" json:"height,omitempty"`
	Caption          *string `protobuf:"bytes,11,opt,name=caption" json:"caption,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AttachmentPointer) Reset()                    { *m = AttachmentPointer{} }
func (m *AttachmentPointer) String() string            { return proto.CompactTextString(m) }
func (*AttachmentPointer) ProtoMessage()               {}
func (*AttachmentPointer) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *AttachmentPointer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AttachmentPointer) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *AttachmentPointer) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AttachmentPointer) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *AttachmentPointer) GetThumbnail() []byte {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *AttachmentPointer) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *AttachmentPointer) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *AttachmentPointer) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *AttachmentPointer) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *AttachmentPointer) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *AttachmentPointer) GetCaption() string {
	if m != nil && m.Caption != nil {
		return *m.Caption
	}
	return ""
}

type GroupContext struct {
	Id               []byte             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type             *GroupContext_Type `protobuf:"varint,2,opt,name=type,enum=signalservice.GroupContext_Type" json:"type,omitempty"`
	Name             *string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Members          []string           `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	Avatar           *AttachmentPointer `protobuf:"bytes,5,opt,name=avatar" json:"avatar,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GroupContext) Reset()                    { *m = GroupContext{} }
func (m *GroupContext) String() string            { return proto.CompactTextString(m) }
func (*GroupContext) ProtoMessage()               {}
func (*GroupContext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *GroupContext) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GroupContext) GetType() GroupContext_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return GroupContext_UNKNOWN
}

func (m *GroupContext) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GroupContext) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GroupContext) GetAvatar() *AttachmentPointer {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type ContactDetails struct {
	Number           *string                `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Avatar           *ContactDetails_Avatar `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Color            *string                `protobuf:"bytes,4,opt,name=color" json:"color,omitempty"`
	Verified         *Verified              `protobuf:"bytes,5,opt,name=verified" json:"verified,omitempty"`
	ProfileKey       []byte                 `protobuf:"bytes,6,opt,name=profileKey" json:"profileKey,omitempty"`
	Blocked          *bool                  `protobuf:"varint,7,opt,name=blocked" json:"blocked,omitempty"`
	ExpireTimer      *uint32                `protobuf:"varint,8,opt,name=expireTimer" json:"expireTimer,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ContactDetails) Reset()                    { *m = ContactDetails{} }
func (m *ContactDetails) String() string            { return proto.CompactTextString(m) }
func (*ContactDetails) ProtoMessage()               {}
func (*ContactDetails) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ContactDetails) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *ContactDetails) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContactDetails) GetAvatar() *ContactDetails_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *ContactDetails) GetColor() string {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return ""
}

func (m *ContactDetails) GetVerified() *Verified {
	if m != nil {
		return m.Verified
	}
	return nil
}

func (m *ContactDetails) GetProfileKey() []byte {
	if m != nil {
		return m.ProfileKey
	}
	return nil
}

func (m *ContactDetails) GetBlocked() bool {
	if m != nil && m.Blocked != nil {
		return *m.Blocked
	}
	return false
}

func (m *ContactDetails) GetExpireTimer() uint32 {
	if m != nil && m.ExpireTimer != nil {
		return *m.ExpireTimer
	}
	return 0
}

type ContactDetails_Avatar struct {
	ContentType      *string `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	Length           *uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContactDetails_Avatar) Reset()                    { *m = ContactDetails_Avatar{} }
func (m *ContactDetails_Avatar) String() string            { return proto.CompactTextString(m) }
func (*ContactDetails_Avatar) ProtoMessage()               {}
func (*ContactDetails_Avatar) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11, 0} }

func (m *ContactDetails_Avatar) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *ContactDetails_Avatar) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type GroupDetails struct {
	Id               []byte               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string              `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Members          []string             `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	Avatar           *GroupDetails_Avatar `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Active           *bool                `protobuf:"varint,5,opt,name=active,def=1" json:"active,omitempty"`
	ExpireTimer      *uint32              `protobuf:"varint,6,opt,name=expireTimer" json:"expireTimer,omitempty"`
	Color            *string              `protobuf:"bytes,7,opt,name=color" json:"color,omitempty"`
	Blocked          *bool                `protobuf:"varint,8,opt,name=blocked" json:"blocked,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GroupDetails) Reset()                    { *m = GroupDetails{} }
func (m *GroupDetails) String() string            { return proto.CompactTextString(m) }
func (*GroupDetails) ProtoMessage()               {}
func (*GroupDetails) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

const Default_GroupDetails_Active bool = true

func (m *GroupDetails) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GroupDetails) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GroupDetails) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GroupDetails) GetAvatar() *GroupDetails_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *GroupDetails) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return Default_GroupDetails_Active
}

func (m *GroupDetails) GetExpireTimer() uint32 {
	if m != nil && m.ExpireTimer != nil {
		return *m.ExpireTimer
	}
	return 0
}

func (m *GroupDetails) GetColor() string {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return ""
}

func (m *GroupDetails) GetBlocked() bool {
	if m != nil && m.Blocked != nil {
		return *m.Blocked
	}
	return false
}

type GroupDetails_Avatar struct {
	ContentType      *string `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	Length           *uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupDetails_Avatar) Reset()                    { *m = GroupDetails_Avatar{} }
func (m *GroupDetails_Avatar) String() string            { return proto.CompactTextString(m) }
func (*GroupDetails_Avatar) ProtoMessage()               {}
func (*GroupDetails_Avatar) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12, 0} }

func (m *GroupDetails_Avatar) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *GroupDetails_Avatar) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*Envelope)(nil), "signalservice.Envelope")
	proto.RegisterType((*Content)(nil), "signalservice.Content")
	proto.RegisterType((*CallMessage)(nil), "signalservice.CallMessage")
	proto.RegisterType((*CallMessage_Offer)(nil), "signalservice.CallMessage.Offer")
	proto.RegisterType((*CallMessage_Answer)(nil), "signalservice.CallMessage.Answer")
	proto.RegisterType((*CallMessage_IceUpdate)(nil), "signalservice.CallMessage.IceUpdate")
	proto.RegisterType((*CallMessage_Busy)(nil), "signalservice.CallMessage.Busy")
	proto.RegisterType((*CallMessage_Hangup)(nil), "signalservice.CallMessage.Hangup")
	proto.RegisterType((*DataMessage)(nil), "signalservice.DataMessage")
	proto.RegisterType((*DataMessage_Quote)(nil), "signalservice.DataMessage.Quote")
	proto.RegisterType((*DataMessage_Quote_QuotedAttachment)(nil), "signalservice.DataMessage.Quote.QuotedAttachment")
	proto.RegisterType((*DataMessage_Contact)(nil), "signalservice.DataMessage.Contact")
	proto.RegisterType((*DataMessage_Contact_Name)(nil), "signalservice.DataMessage.Contact.Name")
	proto.RegisterType((*DataMessage_Contact_Phone)(nil), "signalservice.DataMessage.Contact.Phone")
	proto.RegisterType((*DataMessage_Contact_Email)(nil), "signalservice.DataMessage.Contact.Email")
	proto.RegisterType((*DataMessage_Contact_PostalAddress)(nil), "signalservice.DataMessage.Contact.PostalAddress")
	proto.RegisterType((*DataMessage_Contact_Avatar)(nil), "signalservice.DataMessage.Contact.Avatar")
	proto.RegisterType((*DataMessage_Preview)(nil), "signalservice.DataMessage.Preview")
	proto.RegisterType((*DataMessage_Sticker)(nil), "signalservice.DataMessage.Sticker")
	proto.RegisterType((*NullMessage)(nil), "signalservice.NullMessage")
	proto.RegisterType((*ReceiptMessage)(nil), "signalservice.ReceiptMessage")
	proto.RegisterType((*TypingMessage)(nil), "signalservice.TypingMessage")
	proto.RegisterType((*Verified)(nil), "signalservice.Verified")
	proto.RegisterType((*SyncMessage)(nil), "signalservice.SyncMessage")
	proto.RegisterType((*SyncMessage_Sent)(nil), "signalservice.SyncMessage.Sent")
	proto.RegisterType((*SyncMessage_Sent_UnidentifiedDeliveryStatus)(nil), "signalservice.SyncMessage.Sent.UnidentifiedDeliveryStatus")
	proto.RegisterType((*SyncMessage_Contacts)(nil), "signalservice.SyncMessage.Contacts")
	proto.RegisterType((*SyncMessage_Groups)(nil), "signalservice.SyncMessage.Groups")
	proto.RegisterType((*SyncMessage_Blocked)(nil), "signalservice.SyncMessage.Blocked")
	proto.RegisterType((*SyncMessage_Request)(nil), "signalservice.SyncMessage.Request")
	proto.RegisterType((*SyncMessage_Read)(nil), "signalservice.SyncMessage.Read")
	proto.RegisterType((*SyncMessage_Configuration)(nil), "signalservice.SyncMessage.Configuration")
	proto.RegisterType((*SyncMessage_StickerPackOperation)(nil), "signalservice.SyncMessage.StickerPackOperation")
	proto.RegisterType((*SyncMessage_ViewOnceOpen)(nil), "signalservice.SyncMessage.ViewOnceOpen")
	proto.RegisterType((*AttachmentPointer)(nil), "signalservice.AttachmentPointer")
	proto.RegisterType((*GroupContext)(nil), "signalservice.GroupContext")
	proto.RegisterType((*ContactDetails)(nil), "signalservice.ContactDetails")
	proto.RegisterType((*ContactDetails_Avatar)(nil), "signalservice.ContactDetails.Avatar")
	proto.RegisterType((*GroupDetails)(nil), "signalservice.GroupDetails")
	proto.RegisterType((*GroupDetails_Avatar)(nil), "signalservice.GroupDetails.Avatar")
	proto.RegisterEnum("signalservice.Envelope_Type", Envelope_Type_name, Envelope_Type_value)
	proto.RegisterEnum("signalservice.DataMessage_Flags", DataMessage_Flags_name, DataMessage_Flags_value)
	proto.RegisterEnum("signalservice.DataMessage_ProtocolVersion", DataMessage_ProtocolVersion_name, DataMessage_ProtocolVersion_value)
	proto.RegisterEnum("signalservice.DataMessage_Contact_Phone_Type", DataMessage_Contact_Phone_Type_name, DataMessage_Contact_Phone_Type_value)
	proto.RegisterEnum("signalservice.DataMessage_Contact_Email_Type", DataMessage_Contact_Email_Type_name, DataMessage_Contact_Email_Type_value)
	proto.RegisterEnum("signalservice.DataMessage_Contact_PostalAddress_Type", DataMessage_Contact_PostalAddress_Type_name, DataMessage_Contact_PostalAddress_Type_value)
	proto.RegisterEnum("signalservice.ReceiptMessage_Type", ReceiptMessage_Type_name, ReceiptMessage_Type_value)
	proto.RegisterEnum("signalservice.TypingMessage_Action", TypingMessage_Action_name, TypingMessage_Action_value)
	proto.RegisterEnum("signalservice.Verified_State", Verified_State_name, Verified_State_value)
	proto.RegisterEnum("signalservice.SyncMessage_Request_Type", SyncMessage_Request_Type_name, SyncMessage_Request_Type_value)
	proto.RegisterEnum("signalservice.SyncMessage_StickerPackOperation_Type", SyncMessage_StickerPackOperation_Type_name, SyncMessage_StickerPackOperation_Type_value)
	proto.RegisterEnum("signalservice.AttachmentPointer_Flags", AttachmentPointer_Flags_name, AttachmentPointer_Flags_value)
	proto.RegisterEnum("signalservice.GroupContext_Type", GroupContext_Type_name, GroupContext_Type_value)
}

func init() { proto.RegisterFile("SignalService.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 2809 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xdd, 0x72, 0xdb, 0xc6,
	0xf5, 0x37, 0xf8, 0xcd, 0x43, 0x52, 0x81, 0x37, 0x1a, 0x9b, 0x83, 0xf8, 0x1f, 0x2b, 0x48, 0xe6,
	0x6f, 0xb5, 0x33, 0x65, 0x13, 0xd9, 0xcd, 0x24, 0x8e, 0x27, 0x29, 0x45, 0x42, 0x36, 0x6a, 0x89,
	0x64, 0x96, 0xa4, 0x92, 0x5c, 0xa9, 0x10, 0xb1, 0xa2, 0x50, 0x81, 0x00, 0x03, 0x80, 0xb2, 0x99,
	0x07, 0xc8, 0x55, 0x67, 0xda, 0x9b, 0xbe, 0x42, 0xa7, 0xd3, 0x5e, 0x76, 0xa6, 0xbd, 0x69, 0xa7,
	0xf7, 0x6d, 0x5f, 0xa0, 0x0f, 0xd0, 0x9b, 0x3e, 0x45, 0xe7, 0xec, 0x2e, 0x48, 0x80, 0xa2, 0x29,
	0xc5, 0x93, 0xde, 0x68, 0x70, 0x0e, 0xcf, 0x6f, 0x3f, 0xce, 0x9e, 0x3d, 0xfb, 0x3b, 0x47, 0xf0,
	0x66, 0xdf, 0x19, 0x7b, 0x96, 0xdb, 0x67, 0xc1, 0xa5, 0x33, 0x62, 0x8d, 0x69, 0xe0, 0x47, 0x3e,
	0xa9, 0x85, 0x5c, 0x19, 0x0a, 0xa5, 0xfe, 0xdb, 0x2c, 0x94, 0x0c, 0xef, 0x92, 0xb9, 0xfe, 0x94,
	0x91, 0xf7, 0x21, 0x17, 0xcd, 0xa7, 0xac, 0xae, 0xec, 0x28, 0xbb, 0x5b, 0x7b, 0xf7, 0x1a, 0x29,
	0xd3, 0x46, 0x6c, 0xd6, 0x18, 0xcc, 0xa7, 0x8c, 0x72, 0x4b, 0x72, 0x07, 0x0a, 0xa1, 0x3f, 0x0b,
	0x46, 0xac, 0x9e, 0xd9, 0x51, 0x76, 0xcb, 0x54, 0x4a, 0x44, 0x87, 0xaa, 0xf8, 0x6a, 0x33, 0xc4,
	0xd6, 0x8b, 0x3b, 0xca, 0x6e, 0x8d, 0xa6, 0x74, 0x64, 0x1b, 0xf2, 0x01, 0x73, 0xad, 0x79, 0x3d,
	0xcb, 0xa1, 0x42, 0x20, 0xf7, 0xa0, 0x1c, 0x39, 0x13, 0x16, 0x46, 0xd6, 0x64, 0x5a, 0xcf, 0xef,
	0x28, 0xbb, 0x39, 0xba, 0x54, 0x90, 0xf7, 0xa0, 0xe6, 0xb2, 0xb1, 0x35, 0x9a, 0x1f, 0xb1, 0x30,
	0xb4, 0xc6, 0xac, 0x5e, 0xd8, 0x51, 0x76, 0xab, 0x34, 0xad, 0x24, 0x75, 0x28, 0x8e, 0x7c, 0x2f,
	0x62, 0x5e, 0x54, 0x2f, 0xf1, 0xdf, 0x63, 0x91, 0xbc, 0x0d, 0x80, 0xdb, 0x61, 0xc1, 0xd3, 0x99,
	0x63, 0xd7, 0xcb, 0x7c, 0xe2, 0x84, 0x86, 0xec, 0xc2, 0x1b, 0x42, 0x1a, 0x2c, 0xd6, 0x00, 0x7c,
	0x0d, 0xab, 0x6a, 0xdd, 0x83, 0x1c, 0xfa, 0x81, 0x54, 0xa0, 0x38, 0xec, 0x3c, 0xef, 0x74, 0xbf,
	0xe8, 0xa8, 0xb7, 0xc8, 0x16, 0x40, 0xcb, 0xec, 0x3d, 0x33, 0xe8, 0xc0, 0xf8, 0x72, 0xa0, 0x2a,
	0x44, 0x85, 0xea, 0x73, 0xe3, 0xab, 0x13, 0xe3, 0xcb, 0xd6, 0xb3, 0x66, 0xe7, 0xa9, 0xa1, 0x66,
	0xc8, 0x6d, 0xa8, 0xf5, 0xa8, 0x81, 0xca, 0xfd, 0x61, 0xa7, 0x7d, 0x68, 0xa8, 0x59, 0x1c, 0x81,
	0x1a, 0x2d, 0xc3, 0xec, 0x0d, 0xd4, 0x3c, 0xb9, 0x0b, 0x6f, 0x0e, 0x3b, 0x66, 0xdb, 0xe8, 0x0c,
	0xcc, 0x03, 0xd3, 0x68, 0x9f, 0xf4, 0x8d, 0x4e, 0xdb, 0xa0, 0x6a, 0x41, 0xff, 0x65, 0x16, 0x8a,
	0x2d, 0xb9, 0x8b, 0x27, 0x50, 0xb1, 0xad, 0xc8, 0x8a, 0x7d, 0x80, 0xc7, 0x55, 0xd9, 0xd3, 0x56,
	0x8e, 0xab, 0xbd, 0xb4, 0xa0, 0x49, 0x73, 0x44, 0x87, 0x73, 0x6f, 0x14, 0xa3, 0x33, 0x6b, 0xd1,
	0xfd, 0xa5, 0x05, 0x4d, 0x9a, 0x23, 0x7a, 0x64, 0xb9, 0x6e, 0x8c, 0xce, 0xae, 0x45, 0xb7, 0x96,
	0x16, 0x34, 0x69, 0x8e, 0x68, 0x6f, 0xb6, 0x44, 0xe7, 0xd6, 0xa2, 0x3b, 0xb3, 0x04, 0x3a, 0x61,
	0x4e, 0x0c, 0xd8, 0x0a, 0xd8, 0x88, 0x39, 0xd3, 0x28, 0x1e, 0x20, 0xcf, 0x07, 0xf8, 0xbf, 0x95,
	0x01, 0x68, 0xca, 0x88, 0xae, 0x80, 0xc8, 0x3e, 0xd4, 0xa2, 0xf9, 0xd4, 0xf1, 0xc6, 0xc9, 0x20,
	0xaa, 0x5c, 0x89, 0xf7, 0x41, 0xd2, 0x86, 0xa6, 0x21, 0xfa, 0xdf, 0x73, 0x50, 0x49, 0xec, 0x92,
	0x7c, 0x08, 0x79, 0xff, 0xec, 0x8c, 0x05, 0xf2, 0x30, 0x76, 0x5e, 0xed, 0x90, 0x46, 0x17, 0xed,
	0xa8, 0x30, 0x27, 0x1f, 0x43, 0xc1, 0xf2, 0xc2, 0x17, 0x2c, 0x90, 0xe7, 0xf0, 0xce, 0x06, 0x60,
	0x93, 0x1b, 0x52, 0x09, 0x20, 0xfb, 0x50, 0x76, 0x46, 0x6c, 0x38, 0xb5, 0xad, 0x08, 0xcf, 0x21,
	0xbb, 0x5b, 0xd9, 0x7b, 0x6f, 0x03, 0xda, 0x8c, 0x6d, 0xe9, 0x12, 0x86, 0xd3, 0x9f, 0x5b, 0xde,
	0x78, 0x36, 0x95, 0x47, 0xb1, 0x69, 0xfa, 0x67, 0xdc, 0x90, 0x4a, 0x00, 0x79, 0x08, 0xb9, 0xd3,
	0x59, 0x38, 0x97, 0x47, 0x70, 0x7f, 0x03, 0x70, 0x7f, 0x16, 0xce, 0x29, 0x37, 0xd6, 0x3e, 0x86,
	0x3c, 0xdf, 0x3e, 0xd9, 0x82, 0x8c, 0x63, 0x73, 0x67, 0xe5, 0x68, 0xc6, 0xb1, 0xc9, 0x0e, 0x54,
	0x6c, 0x16, 0x8e, 0x02, 0x67, 0x1a, 0x39, 0xbe, 0x27, 0xb3, 0x49, 0x52, 0xa5, 0x3d, 0x86, 0x82,
	0x70, 0xc0, 0x6b, 0x60, 0x2f, 0xa0, 0xbc, 0xd8, 0xfe, 0x15, 0x38, 0xe6, 0x30, 0x7b, 0x7a, 0xe4,
	0xd8, 0x8b, 0x1c, 0xc6, 0x25, 0xcc, 0x35, 0xf8, 0x75, 0xe8, 0x78, 0xcc, 0xf4, 0x6c, 0xf6, 0x92,
	0xc7, 0x7a, 0x8d, 0xa6, 0x95, 0x44, 0x85, 0x6c, 0x68, 0x0b, 0xf7, 0x95, 0x29, 0x7e, 0x6a, 0x77,
	0x20, 0x87, 0x3b, 0x5e, 0x9d, 0x47, 0xab, 0x43, 0x41, 0xb8, 0x70, 0xf5, 0x17, 0xfd, 0x3f, 0xdb,
	0x50, 0x49, 0x5c, 0x57, 0x42, 0x20, 0x77, 0xea, 0xdb, 0x73, 0x6e, 0x51, 0xa6, 0xfc, 0x9b, 0xec,
	0x43, 0xc5, 0x8a, 0x22, 0x6b, 0x74, 0x3e, 0x61, 0x5e, 0x14, 0xd6, 0x33, 0xfc, 0xbc, 0x57, 0xc3,
	0xac, 0xb9, 0xb0, 0xe8, 0xf9, 0x8e, 0x17, 0xb1, 0x80, 0x26, 0x41, 0xe4, 0x03, 0xc8, 0x8f, 0x03,
	0x7f, 0x36, 0x95, 0xb7, 0xf6, 0xad, 0x15, 0xf4, 0x53, 0xfc, 0x8d, 0xe7, 0x98, 0x97, 0x11, 0x15,
	0x96, 0x98, 0xa4, 0xcf, 0x5c, 0x6b, 0x1c, 0xf2, 0x0d, 0xd6, 0xa8, 0x10, 0xd0, 0xe3, 0xec, 0xe5,
	0xd4, 0x09, 0x18, 0xe6, 0xc3, 0x80, 0x87, 0x40, 0x8d, 0x26, 0x55, 0x98, 0x68, 0xa7, 0x81, 0x7f,
	0xe6, 0xb8, 0xec, 0x39, 0x9b, 0xcb, 0x2c, 0x9d, 0xd0, 0xa4, 0xd3, 0x7c, 0x71, 0x35, 0xcd, 0x7f,
	0x08, 0xf9, 0xaf, 0x67, 0x7e, 0xc4, 0x78, 0xfa, 0xbe, 0xba, 0xcd, 0x84, 0xaf, 0x1a, 0x9f, 0xa3,
	0x1d, 0x15, 0xe6, 0xe4, 0x89, 0x48, 0xfc, 0xd6, 0x28, 0xaa, 0x97, 0xb9, 0x83, 0xf4, 0x0d, 0xc8,
	0x96, 0xb0, 0xa4, 0x31, 0x04, 0xd1, 0xd3, 0x80, 0x5d, 0x3a, 0xec, 0x45, 0x1d, 0xae, 0x45, 0xf7,
	0x84, 0x25, 0x8d, 0x21, 0x88, 0x0e, 0x23, 0x67, 0x74, 0xc1, 0x82, 0x7a, 0x85, 0xaf, 0x7a, 0x13,
	0xba, 0x2f, 0x2c, 0x69, 0x0c, 0x21, 0x1f, 0xc1, 0xdd, 0x80, 0x7d, 0x3d, 0x73, 0x02, 0x66, 0xf7,
	0xf0, 0x9d, 0x1e, 0xf9, 0xee, 0x31, 0x0b, 0x42, 0x8c, 0xe7, 0x2a, 0xf7, 0xee, 0xab, 0x7e, 0x46,
	0x4f, 0x3b, 0xe1, 0xb1, 0xc3, 0x5e, 0x74, 0xbd, 0x11, 0xab, 0x6f, 0xed, 0x28, 0xbb, 0x25, 0x9a,
	0xd0, 0x68, 0x7f, 0xc8, 0x40, 0x9e, 0x3b, 0x69, 0x5d, 0xe0, 0x5b, 0xb3, 0xe8, 0xdc, 0x0f, 0xe2,
	0xc0, 0x17, 0x12, 0x86, 0x1f, 0x86, 0x80, 0x7c, 0x97, 0xf9, 0x37, 0xe9, 0xa7, 0xc3, 0x2f, 0xc7,
	0xfd, 0xf3, 0xc1, 0x75, 0xe7, 0x22, 0xfe, 0xda, 0xcb, 0xb0, 0x4c, 0xc5, 0xa3, 0xf6, 0x6b, 0x05,
	0xd4, 0x55, 0x0b, 0x8c, 0x2d, 0xf9, 0x5a, 0x0f, 0x62, 0x2e, 0x52, 0xa6, 0x49, 0x15, 0xd1, 0xa0,
	0x84, 0x61, 0xd4, 0xb1, 0x26, 0x31, 0xed, 0x58, 0xc8, 0xe4, 0x53, 0x28, 0x47, 0xe7, 0xb3, 0xc9,
	0xa9, 0x67, 0x39, 0xae, 0x0c, 0xf3, 0xeb, 0x2f, 0xc9, 0x12, 0xa2, 0xfd, 0x0d, 0xc4, 0x33, 0x8b,
	0xf1, 0xf0, 0x09, 0xe4, 0x3c, 0x9c, 0x43, 0xa4, 0xf4, 0x07, 0xd7, 0x87, 0x52, 0x03, 0x97, 0x40,
	0x39, 0x88, 0xfc, 0x14, 0x0a, 0xde, 0x6c, 0x72, 0xca, 0x02, 0x99, 0x9a, 0x77, 0x6f, 0x00, 0xef,
	0x9d, 0xfb, 0x1e, 0xa3, 0x12, 0x47, 0x3e, 0x85, 0x3c, 0x9b, 0xe0, 0x36, 0x72, 0x37, 0x1e, 0xc0,
	0x40, 0x7b, 0x2a, 0x60, 0xe4, 0x67, 0x50, 0xb4, 0x6c, 0x3b, 0x60, 0x61, 0x58, 0xcf, 0xf3, 0x11,
	0xde, 0xbf, 0xc9, 0x12, 0xfc, 0x30, 0xb2, 0xdc, 0xa6, 0xc0, 0xd1, 0x78, 0x00, 0xd2, 0x84, 0x82,
	0x75, 0x69, 0x45, 0x56, 0x20, 0xdf, 0xca, 0x1f, 0xdc, 0x60, 0xa8, 0x26, 0x07, 0x50, 0x09, 0x44,
	0x4a, 0xe8, 0x07, 0x63, 0xcb, 0x73, 0xbe, 0xb1, 0x78, 0x9a, 0x2e, 0xf2, 0x93, 0x4b, 0xe9, 0xb4,
	0x3f, 0x29, 0x90, 0xe3, 0xc7, 0x78, 0x0f, 0xca, 0x63, 0xe7, 0x92, 0x79, 0x9d, 0xd8, 0xff, 0x65,
	0xba, 0x54, 0x60, 0xc8, 0x9f, 0x59, 0x13, 0xc7, 0x9d, 0x27, 0x42, 0x20, 0xa1, 0xc1, 0xc0, 0x9e,
	0x06, 0xec, 0xcc, 0x79, 0x29, 0x43, 0x58, 0x4a, 0x3c, 0xd3, 0xcf, 0xce, 0x50, 0x9f, 0x93, 0x99,
	0x9e, 0x4b, 0x38, 0xde, 0xc4, 0xb1, 0x6d, 0x19, 0x52, 0x79, 0x31, 0xde, 0x52, 0xc3, 0x1f, 0x18,
	0x27, 0x9c, 0xba, 0x96, 0x98, 0xb0, 0x20, 0x1f, 0x98, 0xa5, 0x4a, 0xfb, 0xbd, 0x02, 0x79, 0x7e,
	0x7a, 0x98, 0x30, 0x2f, 0x2d, 0x77, 0x16, 0xaf, 0x5a, 0x08, 0xa4, 0x29, 0x99, 0x75, 0x86, 0x33,
	0xeb, 0x1f, 0xdd, 0x34, 0x16, 0x92, 0x54, 0x7b, 0x1b, 0xf2, 0xae, 0x75, 0xca, 0xdc, 0x98, 0x2e,
	0x73, 0x41, 0xdf, 0x93, 0x34, 0xb4, 0x04, 0xb9, 0x67, 0xdd, 0x23, 0x43, 0x55, 0x08, 0x40, 0xe1,
	0xa8, 0xbb, 0x6f, 0x1e, 0x22, 0xdb, 0x2c, 0x41, 0xee, 0x8b, 0x2e, 0x7d, 0xae, 0x66, 0x51, 0xdb,
	0x1a, 0xf6, 0x07, 0xdd, 0x23, 0x35, 0xc7, 0x17, 0xcb, 0x23, 0xe5, 0x7b, 0x5b, 0x2c, 0x1f, 0xed,
	0x7f, 0xb3, 0xd8, 0x7f, 0x66, 0xa0, 0x96, 0x0a, 0x4a, 0x62, 0xa6, 0xaa, 0x94, 0x9f, 0x7c, 0xd7,
	0xa0, 0x5e, 0xbb, 0xcc, 0x4c, 0x62, 0x99, 0x3c, 0x4c, 0xa2, 0x80, 0xb1, 0x38, 0x03, 0x4a, 0x09,
	0xad, 0xa7, 0xfe, 0xa9, 0x1f, 0x47, 0x8f, 0x10, 0x30, 0xae, 0x3d, 0xe6, 0x8c, 0xcf, 0x4f, 0xfd,
	0xe0, 0xdc, 0xf7, 0x6d, 0x19, 0x3e, 0x29, 0x1d, 0x66, 0xd4, 0x91, 0x13, 0xcd, 0x65, 0xe4, 0xf0,
	0x6f, 0x9c, 0x25, 0x60, 0xe3, 0xe5, 0x4d, 0x90, 0x12, 0x66, 0xb7, 0xa9, 0x1f, 0x46, 0x23, 0xdf,
	0x16, 0xcf, 0x5f, 0x99, 0x2e, 0x64, 0x51, 0xd8, 0xcc, 0xbc, 0x28, 0x98, 0xcb, 0xda, 0x25, 0x16,
	0xf5, 0xff, 0xbf, 0xe2, 0xda, 0xd8, 0x9d, 0x99, 0x84, 0x3b, 0xb3, 0xda, 0xcf, 0xa1, 0x20, 0xee,
	0x25, 0xf9, 0x68, 0x71, 0xa5, 0x95, 0x1b, 0xa6, 0xc9, 0xf8, 0x26, 0xdf, 0x83, 0xb2, 0x13, 0xf6,
	0xc4, 0x5b, 0xce, 0x3d, 0x57, 0xa2, 0x4b, 0x85, 0xe6, 0x40, 0x51, 0xbe, 0x8d, 0xc8, 0x8d, 0x66,
	0x81, 0x2b, 0x83, 0x0b, 0x3f, 0xd1, 0x85, 0x91, 0x13, 0xb9, 0xf1, 0xa5, 0x15, 0x02, 0x3e, 0xf7,
	0xce, 0x64, 0x59, 0x4d, 0x5c, 0xbf, 0x12, 0x61, 0xae, 0xfd, 0x4a, 0x81, 0xa2, 0x7c, 0x49, 0xf9,
	0x9d, 0xb7, 0x46, 0x17, 0xa6, 0x78, 0xe0, 0xaa, 0x54, 0x4a, 0xe8, 0x32, 0xfc, 0x42, 0x16, 0x92,
	0x11, 0xb5, 0xa0, 0x14, 0x71, 0x1b, 0xf2, 0xf5, 0x35, 0x6d, 0xc9, 0xed, 0x96, 0x0a, 0xf2, 0x08,
	0x72, 0x58, 0x34, 0x49, 0x5e, 0x7c, 0xfd, 0x92, 0xb8, 0xb5, 0x7e, 0x04, 0xf9, 0x03, 0xce, 0x90,
	0xde, 0x80, 0x8a, 0xd1, 0xc1, 0xf2, 0xad, 0xdf, 0x37, 0xbb, 0x1d, 0x55, 0x21, 0x6f, 0xc1, 0x5d,
	0xe3, 0xcb, 0x9e, 0x49, 0x9b, 0x03, 0xb3, 0xdb, 0x39, 0x19, 0x98, 0x47, 0x06, 0x3d, 0x19, 0xf6,
	0xda, 0xcd, 0x01, 0x86, 0xfe, 0x1d, 0x20, 0x3d, 0xda, 0x3d, 0x30, 0x0f, 0x8d, 0x13, 0x2c, 0x0d,
	0xa5, 0x3e, 0xa7, 0x53, 0x78, 0x63, 0xf5, 0xb9, 0xaf, 0x40, 0xd1, 0xec, 0x98, 0x03, 0xb3, 0x79,
	0xa8, 0xde, 0x22, 0x04, 0xb6, 0x8e, 0x8c, 0x7e, 0xbf, 0xf9, 0xd4, 0x10, 0x23, 0xf6, 0x55, 0x85,
	0xd4, 0xa0, 0x7c, 0x6c, 0x1a, 0x5f, 0x9c, 0x74, 0x3b, 0x2d, 0x1c, 0xba, 0x02, 0xc5, 0xd6, 0x90,
	0x52, 0xa3, 0x33, 0x50, 0x33, 0x5a, 0x46, 0x55, 0xf4, 0x07, 0x50, 0x49, 0x14, 0x58, 0xc2, 0x3f,
	0xb6, 0xed, 0x78, 0x63, 0xe9, 0xb8, 0x58, 0xd4, 0xbf, 0x55, 0x60, 0x2b, 0x5d, 0x49, 0x91, 0x0f,
	0x53, 0x57, 0x4f, 0xdf, 0x58, 0x76, 0x25, 0xef, 0x59, 0x8a, 0xed, 0x21, 0x75, 0x4d, 0xb2, 0x3d,
	0xfd, 0x6d, 0x19, 0xbb, 0x55, 0x28, 0xb5, 0x8d, 0x43, 0xf3, 0xd8, 0xa0, 0x5f, 0xa9, 0xb7, 0x30,
	0x7e, 0xa9, 0xd1, 0x6c, 0xab, 0x8a, 0xfe, 0x3b, 0x05, 0x6a, 0xa9, 0x62, 0x2c, 0x3d, 0x9e, 0xb2,
	0xca, 0x1e, 0x3f, 0x81, 0x82, 0x35, 0x5a, 0x94, 0x02, 0x5b, 0x7b, 0xef, 0x6e, 0x2a, 0xec, 0x1a,
	0x4d, 0x6e, 0x4a, 0x25, 0x04, 0xfd, 0xc1, 0x99, 0xaf, 0x8c, 0x89, 0x2a, 0x8d, 0x45, 0x5d, 0x87,
	0x82, 0xb0, 0x45, 0x9f, 0xf6, 0x07, 0x4d, 0x3a, 0x30, 0xda, 0xea, 0x2d, 0x21, 0x74, 0x7b, 0x3d,
	0x03, 0x97, 0xfa, 0x2f, 0x05, 0x4a, 0xc7, 0x2c, 0x70, 0xce, 0x1c, 0x16, 0xd7, 0x25, 0x91, 0xe3,
	0x89, 0x07, 0x4f, 0x59, 0xd4, 0x25, 0xb1, 0x0a, 0x2d, 0x1c, 0x9b, 0x79, 0x91, 0x13, 0xcd, 0x97,
	0x01, 0x9a, 0x54, 0x91, 0x87, 0x90, 0x0f, 0x23, 0x51, 0xe0, 0xe1, 0x56, 0x56, 0x2b, 0xdd, 0x78,
	0xae, 0x46, 0x1f, 0x8d, 0xa8, 0xb0, 0xc5, 0x61, 0x57, 0xab, 0xec, 0x6a, 0xaa, 0x92, 0xd6, 0xf7,
	0x20, 0xcf, 0x11, 0xb8, 0xfa, 0xb6, 0x71, 0xd0, 0x1c, 0x1e, 0x0e, 0xd4, 0x5b, 0x78, 0x00, 0xc7,
	0x06, 0xe5, 0x8d, 0x07, 0x55, 0x21, 0x5b, 0x00, 0xc3, 0xce, 0x42, 0xce, 0xe8, 0xdf, 0xaa, 0x50,
	0x49, 0xb4, 0x05, 0xb0, 0x00, 0x0c, 0x99, 0x17, 0xc9, 0xf4, 0x71, 0xff, 0xd5, 0x0d, 0x84, 0x46,
	0x1f, 0x99, 0x1f, 0x37, 0x26, 0x9f, 0x41, 0x49, 0xd2, 0xed, 0x50, 0x56, 0xbc, 0xef, 0x6e, 0x00,
	0xca, 0x04, 0x1e, 0xd2, 0x05, 0x08, 0x2b, 0x56, 0x7e, 0x20, 0xa1, 0x4c, 0x16, 0xef, 0x6c, 0x80,
	0xf3, 0x82, 0x26, 0xa4, 0x12, 0x80, 0x0c, 0x1d, 0x49, 0x34, 0x0b, 0x23, 0x79, 0xab, 0xf5, 0x0d,
	0x58, 0x2a, 0x2c, 0x69, 0x0c, 0xc1, 0xed, 0x06, 0xcc, 0xb2, 0x25, 0x97, 0xba, 0xbf, 0x11, 0x6a,
	0xd9, 0x94, 0x1b, 0xe3, 0x94, 0xa7, 0xae, 0x3f, 0xba, 0x60, 0xb6, 0x24, 0x4e, 0x9b, 0xa6, 0xdc,
	0x17, 0x96, 0x34, 0x86, 0x90, 0x87, 0x50, 0xba, 0x94, 0x07, 0xcc, 0x1f, 0x89, 0xca, 0xde, 0xdd,
	0x57, 0x9c, 0x3f, 0x5d, 0x18, 0x92, 0x0e, 0xd4, 0x46, 0xbe, 0x77, 0xe6, 0x8c, 0x67, 0x81, 0x88,
	0xbb, 0x32, 0x47, 0xee, 0x6e, 0x76, 0xf3, 0xd2, 0x9e, 0xa6, 0xe1, 0xc9, 0x04, 0x51, 0x4a, 0x25,
	0x08, 0x32, 0x82, 0x6d, 0x99, 0x2f, 0x7b, 0xd6, 0xe8, 0xa2, 0x3b, 0x65, 0x72, 0x42, 0x51, 0x3c,
	0xfd, 0x78, 0x53, 0x40, 0xac, 0x81, 0xd1, 0xb5, 0x83, 0x91, 0xe7, 0x50, 0xbd, 0x94, 0xa5, 0x4c,
	0x77, 0xca, 0x3c, 0x59, 0x5b, 0x3d, 0xd8, 0x30, 0xf8, 0x71, 0xc2, 0x9c, 0xa6, 0xc0, 0xda, 0x5f,
	0xb3, 0x90, 0xeb, 0xcb, 0x22, 0xe3, 0x9a, 0xab, 0xb9, 0x92, 0xb2, 0x56, 0x52, 0xcc, 0x23, 0x28,
	0x4e, 0x36, 0x76, 0xc0, 0x92, 0xdd, 0xb7, 0xd8, 0x94, 0x3c, 0x86, 0x3a, 0xaf, 0x91, 0xf9, 0x0c,
	0xfd, 0xc8, 0x0a, 0xa2, 0x65, 0x9b, 0x31, 0xc7, 0xa7, 0x78, 0xe5, 0xef, 0xe4, 0x17, 0x40, 0x66,
	0x9e, 0xc8, 0x0c, 0x78, 0xcc, 0x78, 0x7b, 0x67, 0x31, 0xb1, 0x7f, 0x7c, 0xcd, 0xdd, 0x6b, 0x0c,
	0x13, 0xc8, 0x36, 0x73, 0x9d, 0x4b, 0x16, 0xcc, 0xc5, 0x08, 0x74, 0xcd, 0xa8, 0xe4, 0x21, 0xdc,
	0x76, 0x42, 0xca, 0x46, 0xce, 0xd4, 0x61, 0x5e, 0x24, 0x3b, 0x4c, 0x18, 0xbf, 0xa5, 0xc7, 0xf9,
	0x33, 0x9c, 0x86, 0x5e, 0xfd, 0x5d, 0x3b, 0x05, 0xed, 0xd5, 0xd3, 0xdc, 0xc0, 0xe1, 0x3a, 0x54,
	0x93, 0x4b, 0x91, 0xc4, 0x22, 0xa5, 0xd3, 0x46, 0x50, 0x8a, 0x53, 0x02, 0x3e, 0xd0, 0xa7, 0xae,
	0x7f, 0x7a, 0x63, 0xf6, 0xc2, 0xad, 0xc9, 0x3b, 0x98, 0x7f, 0x26, 0x53, 0x97, 0x45, 0x92, 0xba,
	0xc4, 0x3b, 0x5a, 0xa8, 0xb5, 0x4f, 0xa1, 0x20, 0x12, 0xc7, 0xeb, 0x4d, 0xa1, 0x7d, 0x06, 0x45,
	0x79, 0x93, 0xf1, 0xee, 0x88, 0x62, 0x2e, 0xac, 0x2b, 0x3b, 0x59, 0xe4, 0x6b, 0x52, 0x44, 0x96,
	0x27, 0xdf, 0x15, 0xd1, 0xcb, 0xa9, 0xd2, 0x85, 0xac, 0xfd, 0x46, 0x81, 0xa2, 0x4c, 0x3f, 0x58,
	0x83, 0x26, 0x5e, 0xdc, 0x07, 0xd7, 0x27, 0xac, 0xc4, 0xb3, 0xab, 0x1f, 0xad, 0xeb, 0x51, 0x57,
	0xa1, 0xd4, 0xea, 0x76, 0x06, 0xcd, 0xd6, 0xa0, 0x2f, 0x08, 0xf8, 0x53, 0xda, 0x1d, 0xf6, 0xfa,
	0x82, 0x2a, 0xec, 0x1f, 0x76, 0x5b, 0xcf, 0x8d, 0xb6, 0x9a, 0x25, 0xb7, 0xa1, 0xd6, 0xea, 0x76,
	0x0e, 0xcc, 0xa7, 0x43, 0x41, 0x59, 0xd4, 0x9c, 0xf6, 0x04, 0x72, 0x98, 0xda, 0x38, 0x3f, 0x66,
	0x9e, 0x2d, 0x9b, 0x9d, 0xc8, 0x8f, 0xb9, 0xb4, 0xf9, 0xca, 0x68, 0xff, 0x50, 0xa0, 0x96, 0x4a,
	0x34, 0x78, 0xe2, 0x98, 0x24, 0x25, 0x6d, 0x08, 0xf9, 0x68, 0x25, 0x9a, 0xd2, 0x91, 0x03, 0x78,
	0x7b, 0xb6, 0x26, 0xaa, 0x4c, 0xcf, 0x76, 0x46, 0x56, 0xe4, 0x07, 0xa1, 0x8c, 0x93, 0x6b, 0xac,
	0xc8, 0x0f, 0x41, 0x15, 0x0d, 0xdc, 0x04, 0x32, 0xcb, 0x91, 0x57, 0xf4, 0xb8, 0x2e, 0xd7, 0xf1,
	0x2e, 0x24, 0x8b, 0x15, 0xad, 0xaf, 0x12, 0x4d, 0xe9, 0xb4, 0x3f, 0x2a, 0xb0, 0xbd, 0x2e, 0x8b,
	0xbd, 0x06, 0x0f, 0x7d, 0x26, 0x8f, 0x58, 0xbc, 0xf0, 0x8f, 0xbe, 0x63, 0xda, 0x4c, 0x9e, 0xf7,
	0xfd, 0xe5, 0x79, 0x9b, 0x9d, 0xfe, 0xa0, 0x79, 0x88, 0x1c, 0x11, 0xa0, 0x40, 0x8d, 0xa3, 0xee,
	0xb1, 0xa1, 0x2a, 0x5a, 0x1b, 0xaa, 0xc9, 0xec, 0xf8, 0x7a, 0x27, 0xa9, 0xff, 0x39, 0x03, 0xb7,
	0xaf, 0x04, 0x7f, 0xa2, 0xbb, 0x54, 0x88, 0xbb, 0xb2, 0xc9, 0x3e, 0x4e, 0xe6, 0x6a, 0x1f, 0x47,
	0x85, 0xec, 0x05, 0x9b, 0x4b, 0x9a, 0x85, 0x9f, 0x58, 0x27, 0x85, 0xce, 0x37, 0x4c, 0x36, 0x1b,
	0xf9, 0x37, 0x5f, 0xcb, 0xa2, 0xa3, 0x93, 0xe7, 0xb6, 0x4b, 0x05, 0xee, 0xc0, 0x76, 0xc6, 0xf8,
	0xa4, 0x8b, 0x1e, 0xa3, 0x94, 0x52, 0x3d, 0xa2, 0xe2, 0x4a, 0x8f, 0x68, 0xd1, 0xd3, 0x2c, 0x25,
	0x7b, 0x9a, 0xdb, 0x90, 0x7f, 0xe1, 0xd8, 0xd1, 0x39, 0x7f, 0x2f, 0x6b, 0x54, 0x08, 0x38, 0xfe,
	0x39, 0x56, 0x72, 0x11, 0xff, 0x3f, 0x50, 0x8d, 0x4a, 0x89, 0x57, 0x62, 0x96, 0xe8, 0x37, 0x57,
	0x64, 0x25, 0x26, 0x44, 0x5d, 0x8b, 0x4b, 0x80, 0xdb, 0x50, 0x3b, 0xee, 0x9a, 0x2d, 0xe3, 0x44,
	0x52, 0x74, 0x55, 0xd1, 0xbf, 0xcd, 0x40, 0x35, 0xd9, 0x65, 0x4d, 0x38, 0xad, 0xca, 0x9d, 0xf6,
	0x28, 0x55, 0x7a, 0xef, 0x6c, 0x68, 0xd0, 0x26, 0xe9, 0x35, 0x91, 0x8d, 0x2a, 0xd9, 0xb0, 0xe3,
	0xfd, 0xa7, 0x3a, 0xbe, 0x50, 0x22, 0xf5, 0xe4, 0x44, 0xea, 0x91, 0x62, 0xa2, 0xf0, 0xcb, 0x7f,
	0xb7, 0xc2, 0x4f, 0x7f, 0xb6, 0x2e, 0x9f, 0x00, 0x14, 0x64, 0xbd, 0xa2, 0x08, 0x36, 0xc9, 0x19,
	0xbc, 0xa8, 0xe7, 0x3f, 0x1f, 0x9a, 0x03, 0x35, 0x4b, 0x54, 0xa8, 0x52, 0xe3, 0xf3, 0xa1, 0xd1,
	0x1f, 0x9c, 0x98, 0x9d, 0x83, 0xae, 0x9a, 0xd3, 0xff, 0x9d, 0x81, 0x2d, 0x99, 0xc9, 0xdb, 0x2c,
	0xb2, 0x1c, 0x37, 0x44, 0x4f, 0xcb, 0x86, 0x99, 0x8c, 0x45, 0xd9, 0x06, 0x8b, 0x37, 0x97, 0x49,
	0x6c, 0xee, 0xc9, 0x62, 0x0b, 0xe2, 0xf5, 0xbd, 0xf2, 0x7f, 0x8f, 0xd4, 0xd0, 0xab, 0x9d, 0xa8,
	0x6d, 0xc8, 0x8f, 0x7c, 0xd7, 0x0f, 0xe2, 0x3a, 0x9e, 0x0b, 0x29, 0xb2, 0x95, 0xbf, 0x29, 0xd9,
	0xba, 0xae, 0xcd, 0x5d, 0x5f, 0xf2, 0xbf, 0x22, 0xcf, 0x22, 0x0b, 0x6e, 0xb7, 0xd2, 0x42, 0x2f,
	0x5d, 0x69, 0xa1, 0x6b, 0xfb, 0x8b, 0x52, 0xfd, 0xfa, 0x96, 0xe8, 0x1d, 0x28, 0xb8, 0xcc, 0x1b,
	0x47, 0xe7, 0xdc, 0x4d, 0x35, 0x2a, 0x25, 0xfd, 0x2f, 0x71, 0xc0, 0xc5, 0x5e, 0x5e, 0x0d, 0xb8,
	0x75, 0xde, 0x4d, 0x84, 0x4e, 0x36, 0x1d, 0x3a, 0x8f, 0x17, 0x7e, 0x5f, 0x4f, 0xa0, 0x93, 0x53,
	0xad, 0x7a, 0xfd, 0x9e, 0xa8, 0xca, 0x2e, 0x45, 0x83, 0xad, 0xf4, 0x38, 0x17, 0x05, 0x33, 0x46,
	0xa5, 0x6e, 0xd5, 0x1d, 0x85, 0xab, 0xff, 0x51, 0x58, 0x9c, 0x5a, 0x31, 0x79, 0x6a, 0x09, 0x07,
	0x97, 0x52, 0x0e, 0xfe, 0x3e, 0xdc, 0xb7, 0x6f, 0x40, 0xc3, 0x0f, 0xc6, 0x8d, 0x17, 0xe7, 0x4e,
	0x38, 0x65, 0x41, 0x38, 0x0f, 0x23, 0x36, 0x09, 0x57, 0xf6, 0xcc, 0xaf, 0x88, 0x67, 0xb9, 0x8d,
	0xe9, 0x2c, 0x3c, 0xdf, 0x4f, 0xff, 0xcf, 0x9d, 0x17, 0xef, 0xe1, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x24, 0x20, 0x4c, 0x98, 0x89, 0x1f, 0x00, 0x00,
}
