// Code generated by protoc-gen-go.
// source: WebSocketResources.proto
// DO NOT EDIT!

package signalservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WebSocketMessage_Type int32

const (
	WebSocketMessage_UNKNOWN  WebSocketMessage_Type = 0
	WebSocketMessage_REQUEST  WebSocketMessage_Type = 1
	WebSocketMessage_RESPONSE WebSocketMessage_Type = 2
)

var WebSocketMessage_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUEST",
	2: "RESPONSE",
}
var WebSocketMessage_Type_value = map[string]int32{
	"UNKNOWN":  0,
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}
func (x WebSocketMessage_Type) String() string {
	return proto.EnumName(WebSocketMessage_Type_name, int32(x))
}
func (x *WebSocketMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WebSocketMessage_Type_value, data, "WebSocketMessage_Type")
	if err != nil {
		return err
	}
	*x = WebSocketMessage_Type(value)
	return nil
}
func (WebSocketMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{2, 0} }

type WebSocketRequestMessage struct {
	Verb             *string  `protobuf:"bytes,1,opt,name=verb" json:"verb,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Body             []byte   `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Headers          []string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	Id               *uint64  `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *WebSocketRequestMessage) Reset()                    { *m = WebSocketRequestMessage{} }
func (m *WebSocketRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*WebSocketRequestMessage) ProtoMessage()               {}
func (*WebSocketRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *WebSocketRequestMessage) GetVerb() string {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return ""
}

func (m *WebSocketRequestMessage) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WebSocketRequestMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *WebSocketRequestMessage) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebSocketRequestMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type WebSocketResponseMessage struct {
	Id               *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status           *uint32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Message          *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Headers          []string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	Body             []byte   `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *WebSocketResponseMessage) Reset()                    { *m = WebSocketResponseMessage{} }
func (m *WebSocketResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*WebSocketResponseMessage) ProtoMessage()               {}
func (*WebSocketResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *WebSocketResponseMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WebSocketResponseMessage) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *WebSocketResponseMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *WebSocketResponseMessage) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebSocketResponseMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WebSocketMessage struct {
	Type             *WebSocketMessage_Type    `protobuf:"varint,1,opt,name=type,enum=signalservice.WebSocketMessage_Type" json:"type,omitempty"`
	Request          *WebSocketRequestMessage  `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response         *WebSocketResponseMessage `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *WebSocketMessage) Reset()                    { *m = WebSocketMessage{} }
func (m *WebSocketMessage) String() string            { return proto.CompactTextString(m) }
func (*WebSocketMessage) ProtoMessage()               {}
func (*WebSocketMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *WebSocketMessage) GetType() WebSocketMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return WebSocketMessage_UNKNOWN
}

func (m *WebSocketMessage) GetRequest() *WebSocketRequestMessage {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *WebSocketMessage) GetResponse() *WebSocketResponseMessage {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*WebSocketRequestMessage)(nil), "signalservice.WebSocketRequestMessage")
	proto.RegisterType((*WebSocketResponseMessage)(nil), "signalservice.WebSocketResponseMessage")
	proto.RegisterType((*WebSocketMessage)(nil), "signalservice.WebSocketMessage")
	proto.RegisterEnum("signalservice.WebSocketMessage_Type", WebSocketMessage_Type_name, WebSocketMessage_Type_value)
}

func init() { proto.RegisterFile("WebSocketResources.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x3f, 0x4f, 0x83, 0x50,
	0x14, 0xc5, 0x85, 0xa2, 0x6d, 0x5f, 0xff, 0x48, 0xde, 0xa0, 0x8c, 0x84, 0x18, 0x65, 0x62, 0xa8,
	0x8b, 0xa3, 0xa9, 0xc1, 0xc5, 0x48, 0xeb, 0xa3, 0x4d, 0x67, 0x28, 0x37, 0x2d, 0xb1, 0x05, 0x7c,
	0xf7, 0xb5, 0x0d, 0x93, 0x83, 0x9b, 0x9f, 0xda, 0xf0, 0x28, 0x55, 0x9a, 0xd4, 0xed, 0x9e, 0x9b,
	0x73, 0xb8, 0x3f, 0x4e, 0x1e, 0x31, 0x66, 0x10, 0xfa, 0xe9, 0xfc, 0x1d, 0x04, 0x03, 0x4c, 0x37,
	0x7c, 0x0e, 0xe8, 0x64, 0x3c, 0x15, 0x29, 0xed, 0x61, 0xbc, 0x48, 0x82, 0x15, 0x02, 0xdf, 0xc6,
	0x73, 0xb0, 0x3e, 0xc9, 0xf5, 0x1f, 0xeb, 0xc7, 0x06, 0x50, 0xbc, 0x02, 0x62, 0xb0, 0x00, 0x4a,
	0x89, 0xb6, 0x05, 0x1e, 0x1a, 0x8a, 0xa9, 0xd8, 0x6d, 0x26, 0xe7, 0x62, 0x97, 0x05, 0x62, 0x69,
	0xa8, 0xe5, 0xae, 0x98, 0x8b, 0x5d, 0x98, 0x46, 0xb9, 0xd1, 0x30, 0x15, 0xbb, 0xcb, 0xe4, 0x4c,
	0x0d, 0xd2, 0x5c, 0x42, 0x10, 0x01, 0x47, 0xe3, 0xdc, 0x6c, 0xd8, 0x6d, 0x56, 0x49, 0xda, 0x27,
	0x6a, 0x1c, 0x19, 0x9a, 0xa9, 0xd8, 0x1a, 0x53, 0xe3, 0xc8, 0xfa, 0x56, 0xea, 0xb0, 0x59, 0x9a,
	0x20, 0x54, 0x08, 0xa5, 0x59, 0xa9, 0xcc, 0xf4, 0x8a, 0x5c, 0xa0, 0x08, 0xc4, 0x06, 0x25, 0x40,
	0x8f, 0xed, 0x55, 0x71, 0x6e, 0x5d, 0x46, 0x24, 0x45, 0x9b, 0x55, 0xf2, 0x1f, 0x90, 0x0a, 0x5b,
	0xfb, 0xc5, 0xb6, 0xbe, 0x54, 0xa2, 0x1f, 0x60, 0x2a, 0x88, 0x07, 0xa2, 0x89, 0x3c, 0x03, 0x89,
	0xd1, 0x1f, 0xdc, 0x38, 0xb5, 0x02, 0x9d, 0x63, 0xbb, 0x33, 0xc9, 0x33, 0x60, 0x32, 0x41, 0x1f,
	0x49, 0x93, 0x97, 0x9d, 0x4a, 0xde, 0xce, 0xe0, 0xf6, 0x54, 0xb8, 0x5e, 0x3d, 0xab, 0x62, 0xf4,
	0x89, 0xb4, 0xf8, 0xbe, 0x13, 0xf9, 0x67, 0x9d, 0xc1, 0xdd, 0xe9, 0x4f, 0xd4, 0xba, 0x63, 0x87,
	0xa0, 0xe5, 0x10, 0xad, 0x80, 0xa2, 0x1d, 0xd2, 0x9c, 0x7a, 0x2f, 0xde, 0x68, 0xe6, 0xe9, 0x67,
	0x85, 0x60, 0xee, 0xdb, 0xd4, 0xf5, 0x27, 0xba, 0x42, 0xbb, 0xa4, 0xc5, 0x5c, 0x7f, 0x3c, 0xf2,
	0x7c, 0x57, 0x57, 0x87, 0xcf, 0xe4, 0x3e, 0xe5, 0x0b, 0x67, 0xb7, 0x8c, 0x31, 0x03, 0x8e, 0x39,
	0x0a, 0x58, 0xe3, 0xd1, 0xd9, 0x38, 0x11, 0xc0, 0x93, 0x60, 0xe5, 0xec, 0x20, 0x44, 0x79, 0x7f,
	0x78, 0x79, 0x40, 0x19, 0x17, 0x2f, 0x0d, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x1f, 0xd6,
	0x6e, 0x85, 0x02, 0x00, 0x00,
}
