// Code generated by protoc-gen-go.
// source: SubProtocol.proto
// DO NOT EDIT!

package textsecure

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type WebSocketMessage_Type int32

const (
	WebSocketMessage_UNKNOWN  WebSocketMessage_Type = 0
	WebSocketMessage_REQUEST  WebSocketMessage_Type = 1
	WebSocketMessage_RESPONSE WebSocketMessage_Type = 2
)

var WebSocketMessage_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUEST",
	2: "RESPONSE",
}
var WebSocketMessage_Type_value = map[string]int32{
	"UNKNOWN":  0,
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}
func (x WebSocketMessage_Type) String() string {
	return proto.EnumName(WebSocketMessage_Type_name, int32(x))
}
func (x WebSocketMessage_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *WebSocketMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WebSocketMessage_Type_value, data, "WebSocketMessage_Type")
	if err != nil {
		return err
	}
	*x = WebSocketMessage_Type(value)
	return nil
}

type WebSocketRequestMessage struct {
	Verb             *string `protobuf:"bytes,1,opt,name=verb" json:"verb,omitempty"`
	Path             *string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Body             []byte  `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Id               *uint64 `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WebSocketRequestMessage) Reset()         { *m = WebSocketRequestMessage{} }
func (m *WebSocketRequestMessage) String() string { return proto.CompactTextString(m) }
func (*WebSocketRequestMessage) ProtoMessage()    {}

func (m *WebSocketRequestMessage) GetVerb() string {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return ""
}

func (m *WebSocketRequestMessage) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WebSocketRequestMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *WebSocketRequestMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type WebSocketResponseMessage struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status           *uint32 `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Body             []byte  `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WebSocketResponseMessage) Reset()         { *m = WebSocketResponseMessage{} }
func (m *WebSocketResponseMessage) String() string { return proto.CompactTextString(m) }
func (*WebSocketResponseMessage) ProtoMessage()    {}

func (m *WebSocketResponseMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WebSocketResponseMessage) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *WebSocketResponseMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *WebSocketResponseMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WebSocketMessage struct {
	Type             *WebSocketMessage_Type    `protobuf:"varint,1,opt,name=type,enum=textsecure.WebSocketMessage_Type" json:"type,omitempty"`
	Request          *WebSocketRequestMessage  `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response         *WebSocketResponseMessage `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *WebSocketMessage) Reset()         { *m = WebSocketMessage{} }
func (m *WebSocketMessage) String() string { return proto.CompactTextString(m) }
func (*WebSocketMessage) ProtoMessage()    {}

func (m *WebSocketMessage) GetType() WebSocketMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *WebSocketMessage) GetRequest() *WebSocketRequestMessage {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *WebSocketMessage) GetResponse() *WebSocketResponseMessage {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterEnum("textsecure.WebSocketMessage_Type", WebSocketMessage_Type_name, WebSocketMessage_Type_value)
}
